living_room_tv_channel_up:
  alias: Living Room / TV / Channel / Up
  sequence:
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "CHANNELUP"

living_room_tv_channel_down:
  alias: Living Room / TV / Channel / Down
  sequence:
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "CHANNELDOWN"