living_room_tv_iptv:
  alias: Living Room / TV / IPTV 
  sequence:
  - choose:
    # IF living room TV off
    - conditions:
        - condition: state
          entity_id: media_player.living_room_tv
          state: 'off'
      # Switch on TV    
      sequence:
        - service: media_player.turn_on
          entity_id: media_player.living_room_tv
        - wait_template: "{{ is_state('media_player.living_room_tv', 'on') }}"
        - delay: 00:00:02
  - choose:
    # IF Media Source is Not Smart IPTV
    - conditions:
      - condition: template
        value_template: "{{ state_attr('media_player.living_room_tv', 'source') != 'Smart IPTV' }}"
      # Switch TV Source to Smart IPTV
      sequence:
        - service: media_player.select_source
          data:
            entity_id: media_player.living_room_tv
            source: Smart IPTV 
        - wait_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'Smart IPTV') }}"
        - delay: 00:00:02

living_room_tv_iptv_sky_sports:
  alias: Living Room / TV / IPTV / Sky Sports
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "7"

living_room_tv_iptv_sky_sports_football:
  alias: Living Room / TV / IPTV / Sky Sports Football
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "8"

living_room_tv_iptv_food_network:
  alias: Living Room / TV / IPTV / Food Network
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "7"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "5"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "8"

living_room_tv_iptv_history_channel:
  alias: Living Room / TV / IPTV / History Channel
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "3"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "9"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "9"