living_room_tv_channel_up:
  alias: Living Room / TV / Channel / Up
  sequence:
    choose:
      # IF living room TV source is Melita
      - conditions:
        - condition: template
          value_template: "{{ state_attr('media_player.living_room_tv', 'source') == 'Melita' }}"
        # Melita Channel Up   
        sequence:
          - service: remote.send_command
            data:
              entity_id: remote.living_room_rm_pro_remote
              device: Melita
              command:
                - CHANNELUP
      # IF living room TV source is Smart IPTV
      - conditions:
        - condition: template
          value_template: "{{ state_attr('media_player.living_room_tv', 'source') == 'Smart IPTV' }}"
        # WebOsTV Channel Up
        sequence:    
          - service: webostv.button
            data:
              entity_id: media_player.living_room_tv
              button: "CHANNELUP"

living_room_tv_channel_down:
  alias: Living Room / TV / Channel / Down
  sequence:
    choose:
      # IF living room TV source is Melita
      - conditions:
        - condition: template
          value_template: "{{ state_attr('media_player.living_room_tv', 'source') == 'Melita' }}"
        # Melita Channel Up   
        sequence:
          - service: remote.send_command
            data:
              entity_id: remote.living_room_rm_pro_remote
              device: Melita
              command:
                - CHANNELDOWN
      # IF living room TV source is Smart IPTV
      - conditions:
        - condition: template
          value_template: "{{ state_attr('media_player.living_room_tv', 'source') == 'Smart IPTV' }}"
        # WebOsTV Channel Up
        sequence:    
          - service: webostv.button
            data:
              entity_id: media_player.living_room_tv
              button: "CHANNELDOWN"