######################################################################################################
# @Automation
# @Alias: Plex / Library Refresh
######################################################################################################
- id: 'Plex / Library Refresh'
  alias: Plex / Library Refresh

  #trigger
  trigger:
    - platform: time
      at: !secret plex_library_refresh_run_time

  #action
  action:
    - service: script.plex_library_refresh
