######################################################################################################
# @Automation
# @Alias: Pre Match Day / Hour
# @Trigger:
#  - Pre Match Day Hour / Binary Sensor / On
# @Action:
#  - Notify /Living Room Sounbar
#  - Notify / Mark / App
######################################################################################################
- id: 'PreMatchDayHour'
  alias: Pre Match Day / Hour

  #trigger
  trigger:
    - platform: state
      entity_id: binary_sensor.pre_matchday_hour_sensor
      from: 'off'
      to: 'on' 

  #action
  action:
    - service: script.notify_base_app_mark
      data:
        title: "The Loft Match Update"
        message: "{{ state_attr('calendar.manchester_united_matches', 'message') + ' kicking off in one hour!' }}"
    - service: script.notify_base_living_soundbar
      data:
        title: "The Loft Match Update"
        message: "{{ state_attr('calendar.manchester_united_matches', 'message') + ' kicking off in one hour!' }}"
    - service: script.notify_base_tv
      data:
        title: "The Loft Match Update"
        message: "{{ state_attr('calendar.manchester_united_matches', 'message') + ' kicking off in one hour!' }}"