######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / On / Morning
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Time / InputDateTime
# @Action:
#  - Water Heater / On
######################################################################################################
- id: 'ShowerWaterHeaterOnMorning'
  alias: Shower / Water Heater / On / Morning
  description: 'Switch On Water Heater at Set Intervals'

  #trigger
  trigger:
  - platform: time
    at: input_datetime.shower_morning_time
  
  #action
  action:
  - service: switch.turn_on
    entity_id: switch.spare_bathroom_water_heater_sw

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / On / Evening
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Time / InputDateTime
# @Action:
#  - Water Heater / On
######################################################################################################
- id: 'ShowerWaterHeaterOnEvening'
  alias: Shower / Water Heater / On / Evening
  description: 'Switch On Water Heater at Set Intervals'

  #trigger
  trigger:
  - platform: time
    at: input_datetime.shower_evening_time
  
  #action
  action:
  - service: switch.turn_on
    entity_id: switch.spare_bathroom_water_heater_sw

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / Off / 90
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Switch / On / 90 mins
# @Action:
#  - Water Heater / Off
#  - Delay / 5 Minutes
#  - Condition / Water Heater / On
#  - Water Heater / Off
#  - Delay / 5 Minutes
#  - Condition / Water Heater / On
#  - Notify / Base TTS

######################################################################################################
- id: 'ShowerWaterHeaterOff90'
  alias: Shower / Water Heater / Off / 90
  description: 'Switch Off Water Heater after switched off for 90mins'

  #trigger
  trigger:
  - platform: state
    entity_id: switch.spare_bathroom_water_heater_sw
    from: 'off'
    to: 'on'
    for: 
      minutes: '90'

  #action
  action:
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - service: script.notify_base_tts
    data:
      title: "The Loft Notification"
      message: "Shower Water Heater is Warm. Water Heater is now switched off."
  - delay: 00:05:00
  - condition: state
    entity_id: switch.spare_bathroom_water_heater_sw
    state: 'on'
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - delay: 00:05:00
  - condition: state
    entity_id: switch.spare_bathroom_water_heater_sw
    state: 'on'
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Shower Water Heater is Still Switched On. Turn off now."

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / Off / 60
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Switch / On / 60 mins
# @Action:
#  - Water Heater / Off
#  - Delay / 5 Minutes
#  - Condition / Water Heater / On
#  - Water Heater / Off
#  - Delay / 5 Minutes
#  - Condition / Water Heater / On
#  - Notify / Base TTS
######################################################################################################
- id: 'ShowerWaterHeaterOff60'
  alias: Shower / Water Heater / Off / 60
  description: 'Switch Off Water Heater after switched off for 60mins'

  #trigger
  trigger:
  - platform: state
    entity_id: switch.spare_bathroom_water_heater_sw
    from: 'off'
    to: 'on'
    for: 
      minutes: '60'

  #action
  action:
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - service: script.notify_base_tts
    data:
      title: "The Loft Notification"
      message: "Shower Water Heater is Warm. Water Heater is now switched off."
  - delay: 00:05:00
  - condition: state
    entity_id: switch.spare_bathroom_water_heater_sw
    state: 'on'
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - delay: 00:05:00
  - condition: state
    entity_id: switch.spare_bathroom_water_heater_sw
    state: 'on'
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Shower Water Heater is Still Switched On. Turn off now."