- id: 'KitchenACLivingRoomDoorAlert'
  alias: Kitchen AC / Living Room Door / Alert
  description: "Alerts if Living Room Door is open whilst trying to switch on Kitchen Air Conditioner."
  trigger:
  - platform: template
    value_template: '{{ is_state("climate.kitchen_ac", "off") == false }}'
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  action:
  - delay: 00:02:00
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - service: script.notify_base_living_room_tv
    data:
      message: "The Loft Alert: Close Living Room Door for Kitchen AC to remain switched on." 
  - data:
      message: Close Living Room Door for Kitchen AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.mobile_app_the_loft_ha_wifi
  - data:
      gw_mac: 7C:49:EB:1C:F2:2F
      ringtone_id: 12
    service: xiaomi_aqara.play_ringtone
  - delay: 0:02
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - data: {}
    entity_id: climate.kitchen_ac
    service: climate.turn_off
  - data:
      message: Living Room Door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.living_room_tv
  - data:
      message: Living Room Door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.mobile_app_the_loft_ha_wifi