- platform: template
  sensors:
    light_availability_sensor:
      friendly_name: 'Light Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{ 
          states.light
            |selectattr('state','in',['unavailable'])
            |list|count > 0
        }}
      attribute_templates: 
        message: >-
          {%- for light in states.light %}
            {%- if light.state|string == "unavailable" -%}
              {{ light.name }} is {{ light.state + ". "}}
            {%- endif %}
          {%- endfor %}