- platform: template
  sensors:    
    media_availability_sensor:
      friendly_name: 'Media Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{
          states.media_player
            |selectattr('state','in',['unavailable'])
            |list|count > 0
        }}
      attribute_templates: 
        message: >-
          {%- for media in states.media_player %}
            {%- if media.state|string == "unavailable" %}
              {{ media.name }} is {{ media.state }}!
            {%- endif %}
          {%- endfor %}