- platform: template
  sensors:    
    media_availability_sensor:
      friendly_name: 'Media Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{
          states.media_player
            |selectattr('state','in',['unavailable'])
            |rejectattr('entity_id', 'equalto', 'media_player.plex_plex_for_lg_lg_oled55c8lla')
            |list|count > 0
        }}
      attribute_templates: 
        message: >-
          {%- for media in states.media_player %}
            {%- if media.state|string == "unavailable" %}
              {%- if media.name|string != "Plex (Plex for LG - LG OLED55C8LLA)" %}
                {{ media.name }} is {{ media.state }}!
              {%- endif %}
            {%- endif %}
          {%- endfor %}