#################################################################
# @Automation
# @Description: Sends Notification if Away for 15 minutes and
# vacuum has not been switched on for the day.
# @Device: Xiaomi Vacuum (1st Generation)
# @Device_URL: 
# @Trigger: Away
# @Action: Sends Notification
#################################################################
- id: 'VacuumNotifyLocationLeave'
  alias: Vacuum / Notify / Location Leave
  trigger:
  - platform: state
    entity_id: group.the_loft_members
    from: home
    to: not_home
    for: 0:15
  condition:
  - condition: template
    value_template: '{{ (state_attr("input_datetime.last_vacuum_clean", "day")|int) != (now().strftime("%-d")|int) }}'
  action:
  - service: script.notify_vacuum_app
  mode: single

#################################################################
# @Automation
# @Description: Switches on Vacuum from IOS action.
# @Device: Xiaomi Vacuum (1st Generation)
# @Device_URL:
# @Trigger: IOS Event 
# @Action: Starts Vacuum
#################################################################
- id: 'VacuumNotifyAction'
  alias: Vacuum / Notify / Action
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_VACUUM
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: START_VACUUM
  action:
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single

#################################################################
# @Automation
# @Description: Sets input_datetime.last_vacuum_clean to
# todays date if vacuum has cleaned for 15 minuntes.
# @Device: Xiaomi Vacuum (1st Generation)
# @Trigger: Vacuum Cleans For 15 minutes
# @Action: Sets Input DateTime to Today's date
#################################################################
- id: 'VacuumHelperDateSet'
  alias: 'Vacuum / Helper / Date / Set'
  trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    attribute: status
    from: Charging
    to: Cleaning
    for: 00:15:00
  action:
  - service: input_datetime.set_datetime
    data:
      datetime: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
    entity_id: input_datetime.last_vacuum_clean
  mode: single