######################################################################################################
# @Automation
# @Room: Nursery
# @Alias: Nursery Motion Sensor / Motion Detected / Switch On Nursery Lights
######################################################################################################
- id: "NurseryMotionSensorMotionDetectedSwitchOnNurseryLights"
  alias: Nursery Motion Sensor / Motion Detected / Switch On Nursery Lights
  description: "Switch On Nursery Lights against Motion"

  #trigger
  trigger:
    - entity_id: binary_sensor.lumi_lumi_sensor_motion_5fc73e02_ias_zone
      platform: state
      from: "off"
      to: "on"

  #action
  action:
    - service: light.turn_on
      entity_id: light.bedroom_bulb_3_socket_1

######################################################################################################
# @Automation
# @Room: Nursery
# @Alias: Nursery Motion Sensor / Motion Not Detected / Switch Off Nursery Lights
######################################################################################################
- id: "NurseryMotionSensorMotionNotDetectedSwitchOffNurseryLights"
  alias: Nursery Motion Sensor / Motion Not Detected / Switch Off Nursery Lights

  #trigger
  trigger:
    - entity_id: binary_sensor.lumi_lumi_sensor_motion_5fc73e02_ias_zone
      platform: state
      from: "on"
      to: "off"

  #action
  action:
    - service: light.turn_off
      entity_id: light.bedroom_bulb_3_socket_1
