turn_off_kitchen_devices:
  alias: Room / Kitchen / Devices / Off
  sequence:
  - data: {}
    entity_id: light.kitchen_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.kitchen_bulb_2
    service: light.turn_off
  - data: {}
    entity_id: climate.kitchen_ac
    service: climate.turn_off
  mode: single
turn_off_living_room_devices:
  alias: Room / Living Room / Devices / Off
  sequence:
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_off
  - data: {}
    entity_id: climate.living_room_ac
    service: climate.turn_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.72627180bcddc292737e
  mode: single
turn_on_bedroom_lights:
  alias: Room / Bedroom / Lights / On
  sequence:
  - data: {}
    entity_id: light.bedroom_bulb_1
    service: light.turn_on
  - data: {}
    entity_id: light.bedroom_bulb_2
    service: light.turn_on
  mode: single
turn_off_rack_room_lights:
  alias: Room / Rack Room / Lights / Off
  sequence:
  - data: {}
    entity_id: light.rack_room_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.rack_room_bulb_2
    service: light.turn_off
  - data: {}
    entity_id: light.rack_room_bulb_3
    service: light.turn_off
  mode: single
turn_off_bedroom_lights:
  alias: Room / Bedroom / Lights / Off
  sequence:
  - data: {}
    entity_id: light.bedroom_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.bedroom_bulb_2
    service: light.turn_off
  - data: {}
    entity_id: switch.bedroom_bulb_3
    service: switch.turn_off
  mode: single
turn_off_main_staircase_lights:
  alias: Room / Main Staircase / Lights / Off
  sequence:
  - data: {}
    entity_id: light.mainstaircase_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.mainstaircase_bulb_2
    service: light.turn_off
  mode: single
turn_on_main_staircase_lights:
  alias: Room / Main Staircase / Lights / On
  sequence:
  - data: {}
    entity_id: light.mainstaircase_bulb_1
    service: light.turn_on
  - data: {}
    entity_id: light.mainstaircase_bulb_2
    service: light.turn_on
  mode: single
turn_on_hall_light:
  alias: Room / Hall / Light / On
  sequence:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_on
  mode: single
turn_off_hall_light:
  alias: Room / Hall / Light / Off
  sequence:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_off
  mode: single
turn_on_lights_office:
  alias: Room / Office / Lights / On
  sequence:
  - service: light.turn_on
    data: {}
    entity_id: light.office_light_1, light.office_light_2
  mode: single
room_office_lights_off:
  alias: ' Room / Office / Lights / Off'
  sequence:
  - service: light.turn_off
    data: {}
    entity_id: light.office_light_1, light.office_light_2
  mode: single
room_office_devices_off:
  alias: Room / Office / Devices / Off
  sequence:
  - service: climate.turn_off
    data: {}
    entity_id: climate.office_ac
  mode: single
room_office_off:
  alias: Room / Office / Off
  sequence:
  - service: script.room_office_lights_off
    data: {}
  - service: script.room_office_devices_off
    data: {}
  mode: single
room_living_room_lights_off:
  alias: Room / Living Room / Lights / Off
  sequence:
  - service: switch.turn_off
    data: {}
    entity_id: switch.72627180bcddc292737e
  - service: light.turn_off
    data: {}
    entity_id: light.living_room_lights
  mode: single
room_living_room_off:
  alias: Room / Living Room / Off
  sequence:
  - service: script.room_living_room_lights_off
    data: {}
  - service: script.turn_off_living_room_devices
    data: {}
  mode: single