######################################################################################################
# @Automation
# @Alias: Submarine Mode / On
######################################################################################################
- id: 'SubmarineModeOn'
  alias: Submarine Mode / On
  description: 'Turn Sumbarine Mode On'

  #trigger
  trigger:
  - entity_id: input_boolean.submarine_mode
    platform: state
    from: 'off'
    to: 'on'
  
  #action
  action:
  # disable automations (hall and library)
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.hall_automation_override
      - input_boolean.library_automation_override

  # switch on lights (bedroom bulb, hall and kitchen light)
  - service: light.turn_on
    entity_id:
      - light.bedroom_bulb_2
      - light.hall_bulb
      - light.living_room

  - service: switch.turn_on
    data:
      entity_id: switch.living_room_bulb_1_socket_1

######################################################################################################
# @Automation
# @Alias: Submarine Mode / Off
######################################################################################################
- id: 'SubmarineModeOff'
  alias: Submarine Mode / Off
  description: 'Turn Sumbarine Mode Off'

  #trigger
  trigger:
  - entity_id: input_boolean.submarine_mode
    platform: state
    from: 'on'
    to: 'off'
  
  #action
  action:
  # disable automations (hall and library)
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.hall_automation_override
      - input_boolean.library_automation_override

  # switch on lights (bedroom bulb, hall and kitchen light)
  - service: light.turn_off
    entity_id:
      - light.bedroom_bulb_2
      - light.hall_bulb
      - light.living_room

  - service: switch.turn_off
    data:
      entity_id: switch.living_room_bulb_1_socket_1
