######################################################################################################
# @Automation
# @Alias: Submarine Mode / On / Off
######################################################################################################
- id: 'SubmarineModeOn'
  alias: Submarine Mode / On / Off
  description: 'Turn Sumbarine Mode On and Off'

  #trigger
  trigger:
  - entity_id: input_boolean.submarine_mode
    platform: state
    from: 'off'
    to: 'on'
  
  #action
  action:
  - service: script.routine_submarine_mode
  - wait_for_trigger:
      platform: state
      entity_id: input_boolean.submarine_mode
      from: "on"
      to: "off"
  - service: script.routine_submarine_mode_off