######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Motion Detected / Switch On Office Light 1
######################################################################################################
- id: 'StudyMotionSensorMotionDetectedSwitchOnOfficeLight1'
  alias: Study Motion Sensor / Motion Detected / Switch On Office Light 1
  description: 'Switch On Office Light 1 against Motion'

  #trigger
  trigger:
  - entity_id: group.study_motion_sensors
    platform: state
    from: 'off'
    to: 'on'
  
  #condition
  condition:
  - condition: state
    entity_id: input_boolean.study_automation_override
    state: 'off'
    
  #action
  action:
  - service: light.turn_on
    data:
      brightness: 170
      entity_id:
        - light.office_light_1

######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Occupancy Not Detected / Switch Off Office Light 1
######################################################################################################
- id: 'StudyMotionSensorOccupancyNotDetectedSwitchOffOfficeLights'
  alias: Study Motion Sensor / Occupancy Not Detected / Switch Off Office Lights

  #trigger
  trigger:
  - entity_id: group.study_occupancy_sensors
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 2

  #condition
  condition:
  - condition: state
    entity_id: input_boolean.study_automation_override
    state: 'off'
  - condition: state
    entity_id: input_boolean.wfh_mode
    state: 'on'

  #action
  action:
  - service: light.turn_off
    data:
      entity_id:
        - light.office_light_1
        - light.office_light_2

######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Motion Not Detected / Switch Off Office Lights
######################################################################################################
- id: 'StudyMotionSensorMotionNotDetectedSwitchOffOfficeLights'
  alias: Study Motion Sensor / Motion Not Detected / Switch Off Office Lights

  #trigger
  trigger:
  - entity_id: group.study_motion_sensors
    platform: state
    from: 'on'
    to: 'off'

  #condition
  condition:
  - condition: state
    entity_id: input_boolean.study_automation_override
    state: 'off'
  - condition: state
    entity_id: input_boolean.wfh_mode
    state: 'off'
  
  #action
  action:
  - service: light.turn_off
    data:
      entity_id:
        - light.office_light_1
        - light.office_light_2

  