######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Motion Detected / Switch On Office Light 1
######################################################################################################
- id: 'StudyMotionSensorMotionDetectedSwitchOnOfficeLight1'
  alias: Study Motion Sensor / Motion Detected / Switch On Office Light 1
  description: 'Switch On Office Light 1 against Motion'

  #trigger
  trigger:
  - entity_id: group.study_motion_sensors
    platform: state
    from: 'off'
    to: 'on'
  
  #condition
  condition:
  - condition: state
    entity_id: input_boolean.study_automation_override
    state: 'off'
    
  #action
  action:
  - service: light.turn_on
    entity_id: light.office_light_1

######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Occupancy Not Detected / Switch Off Office Light 1
######################################################################################################
- id: 'StudyMotionSensorOccupancyNotDetectedSwitchOffOfficeLights'
  alias: Study Motion Sensor / Occupancy Not Detected / Switch Off Office Lights

  #trigger
  trigger:
  - entity_id: group.study_occupancy_sensors
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 2

  #condition
  condition:
  - condition: state
    entity_id: input_boolean.study_automation_override
    state: 'off'
  
  #action
  action:
  - service: light.turn_off
    data:
      entity_id:
        - light.office_light_1
        - light.office_light_2

######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Motion Not Detected / 5 minutes / Switch Off Office Lights
# @Device: LightWave Smart Dimmer (2 Gang)
# @Device_URL: https://lightwaverf.com/collections/all/products/l22-smart-dimmer-2-gang
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Not Detected / 5 mins
# @Condition
#  - Study Automation Override / Off
# @Action:
#  - Office Light 1 / Off
#  - Office Light 2 / Off
#  - Automation / Regular Motion / On
######################################################################################################
# - id: 'StudyMotionSensorMotionNotDetected5minsSwitchOffOfficeLights'
#   alias: Study Motion Sensor / Motion Not Detected / 5 mins / Switch Off Office Lights

#   #trigger
#   trigger:
#   - entity_id: group.study_motion_sensors
#     platform: state
#     to: 'off'
#     for:
#       minutes: 5
  
#   #condition
#   condition:
#     - condition: state
#       entity_id: input_boolean.study_automation_override
#       state: 'off'
  
#   #action
#   action:
#   - service: light.turn_off
#     data:
#       entity_id:
#         - light.office_light_1
#         - light.office_light_2
#   - service: automation.turn_on
#     entity_id: automation.study_motion_sensor_motion_not_detected_switch_off_office_lights

######################################################################################################
# @Automation
# @Room: Study
# @Alias: Study Motion Sensor / Motion Detected / 5 mins / Extend Automation Time
# @Device: LightWave Smart Dimmer (2 Gang)
# @Device_URL: https://lightwaverf.com/collections/all/products/l22-smart-dimmer-2-gang
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Detected / 5 mins
# @Condition
#  - Study Automation Override / Off
# @Action:
#  - Automation / Regular Motion / Off
######################################################################################################
# - id: 'StudyMotionSensorMotionDetected5minsExtendAutomationTime'
#   alias: Study Motion Sensor / Motion Detected / 5 mins / Extend Automation Time

#   #trigger
#   trigger:
#   - entity_id: group.study_motion_sensors
#     platform: state
#     to: 'on'
#     for:
#       minutes: 5

#   #condition
#   condition:
#     - condition: state
#       entity_id: input_boolean.study_automation_override
#       state: 'off'
  
#   #action
#   action:
#   - service: automation.turn_off
#     entity_id: automation.study_motion_sensor_motion_not_detected_switch_off_office_lights
