######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room Button / Single Click / Toggle Living Room Bulb
######################################################################################################
- id: 'LivingRoomButtonSingleClickToggleLivingRoomBulb'
  alias: Living Room Button / Single Click / Toggle Living Room Bulb
  description: 'Toggles Living Room Bulb on Single Click'
  
  #trigger
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003e7c53f
      click_type: single

  #action
  action:
    service: switch.toggle
    entity_id: switch.living_room_bulb_1_socket_1

######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room Button / Double Click / Toggle Living Room Light
######################################################################################################
- id: 'LivingRoomButtonDoubleClickToggleLivingRoomLight'
  alias: Living Room Button / Double Click / Toggle Living Room Light

  #trigger
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003e7c53f
      click_type: double
  
  #action
  action:
    service: light.toggle
    data:
      entity_id: light.living_room_lights
      transition: 1
      brightness: 255

######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room Button / Long Press Click / Routine / Night
######################################################################################################
- id: 'LivingRoomButtonLongPressClickRoutineNight'
  alias: Living Room Button / Long Press Click / Routine / Night

  #trigger
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003e7c53f
      click_type: long_click_press
  
  #action
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode