######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Kitchen AC / Living Room AC / Living Room Door / Alert
# @Device: Xiaomi Mi Door Window Sensor
# @Device_URL: https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mi-door-window-sensors/
# @Device: Gree Air Conditioner / Fairy Series
# @Device_URL: https://btmalta.com/product/gree-fairy-wall-mounted-type/
# @Trigger:
#  - Living Room Door / Open
# @Condition:
#  - Living Room AC / ON
#  - Kitchen AC / ON
# @Action:
#  - Delay / 2 Minutes
#  - Condition / Kitchen AC / ON
#  - Condition / Living Room AC / ON
#  - Condition / Living Room Door / Open
#  - Condition / Kitchen AC / ON
#  - Script / Notify / Base
# @Action Follow Up:
#  - Delay / 2 Minutes
#  - Condition / Kitchen AC / ON
#  - Condition / Living Room AC / ON
#  - Condition / Living Room Door / Open
#  - Kitchen AC / Off
#  - Living Room AC / Off
#  - Script / Notify / Base
######################################################################################################
- id: 'KitchenACLivingRoomACLivingRoomDoorAlert'
  alias: Kitchen AC / Living Room AC / Living Room Door / Alert
  description: "Alerts if Living Room Door is open whilst Living Room or Kitchen AC is on. If Living 
  Room door is not closed, Living Room AC and Kitchen AC are switched off."

  #trigger
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    from: 'off'
    platform: state
    to: 'on'
  
  #condition
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ (is_state("climate.1e5418e7", "off") == false) }}'
        - condition: template
          value_template: '{{ (is_state("climate.1e541900", "off") == false) }}'

  # action
  action:
  - delay: 00:0w:00
  - condition: template
    value_template: '{{ (is_state("climate.1e5418e7", "off") == false) }}'
  - condition: template
    value_template: '{{ (is_state("climate.1e541900", "off") == false) }}'
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    state: 'on'
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Living Room Door is Open! Close living room door for Kitchen AC to remain switched on."
  
  # action follow up
  - delay: 00:02:00
  - condition: template
    value_template: '{{ (is_state("climate.1e5418e7", "off") == false) }}'
  - condition: template
    value_template: '{{ (is_state("climate.1e541900", "off") == false) }}'
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    state: 'on'
  - service: climate.turn_off
    entity_id:
      - climate.1e5418e7
      - climate.1e541900
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Kitchen AC has been switched off."