######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room / Side Lamp / Time / On
# @Trigger:
#  - Time / Input Boolean / Chill Time
# @Condition:
#  - Living Room TV / On
#  - The Loft Members / Home 
# @Action:
#  - Living Room Lamp / Switch / On
######################################################################################################
- id: 'LivingRoomSideLampTimeOn'
  alias: Living Room / Side Lamp / Time / On
  description: 'Turns the Living Room Side Lamp On at a certain Time.'
  
  # trigger
  trigger:
    - platform: time
      at: input_datetime.chill_time
  
  # condition
  condition:
    - condition: state
      entity_id: media_player.living_room_tv
      state: 'on'
    - condition: state
      entity_id: group.the_loft_members
      state: 'home'

  #action
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_bulb_1_socket_1 
