- id: 'KitchenLampOnSetColor'
  alias: Kitchen Lamp / On / Set Color
  description: 'Adjust Kitchen Lamp Color'

  #trigger
  trigger:
    - platform: state
      entity_id:
        - light.kitchen_lamp
      from: 'off'
      to: 'on'

  #action
  action:
    - alias: 'Set Light and Dim Lights if Dimmed Mode is On'
      choose:
        # IF Dimmed Mode is On
        conditions:
          - condition: state
            entity_id: input_boolean.dimmed_mode
            state: 'on'

        # Set Kitchen Bulbs in Dimmed Mode
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.kitchen_lamp
              brightness: 5

      default:
        # Set Kitchen Bulbs in Non Dimmed Mode
        - service: light.turn_on
          data:
            entity_id:
              - light.kitchen_lamp
            brightness: 100

  mode: parallel
