######################################################################################################
# @Automation
# @Room: Kitchen
# @Device: Gree Air Conditioner / Fairy Series
# @Device_URL: https://btmalta.com/product/gree-fairy-wall-mounted-type/
# @Device: Xiaomi Mi Door Window Sensor
# @Device_URL: https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mi-door-window-sensors/
# @Trigger:
#  - Kitchen AC / ON
# @Condition:
#  - Living Room Door / Open
# @Action:
#  - Delay / 2 Minutes
#  - Condition / Kitchen AC / ON
#  - Condition / Living Room Door / Open
#  - Script / Notify / Base
# @Action Follow Up:
#  - Delay / 2 Minutes
#  - Condition / Kitchen AC / ON
#  - Condition / Living Room Door / Open
#  - Kitchen AC / Off
#  - Script / Notify / Base
######################################################################################################
- id: 'KitchenACLivingRoomDoorAlert'
  alias: Kitchen AC / Living Room Door / Alert
  description: "Alerts if Living Room Door is open whilst trying to switch on Kitchen Air Conditioner."
  
  # trigger
  trigger:
  - platform: template
    value_template: '{{ is_state("climate.1e5418e7", "off") == false }}'
  
  # condition
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    state: 'on'
  
  # action
  action:
  - delay: 00:02:00
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    state: 'on'
  - condition: template
    value_template: '{{ (is_state("climate.1e5418e7", "off") == false) }}'
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Living Room Door is Open! Close Living Room Door for Kitchen AC to remain switched on."
      
  # action follow up
  - delay: 00:02:00
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002b771b8
    state: 'on'
  - condition: template
    value_template: '{{ (is_state("climate.1e5418e7", "off") == false) }}'
  - service: climate.turn_off
    entity_id: climate.1e5418e7
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Living Room Door still open. Kitchen AC has been switched off."