######################################################################################################
# @Automation
# @Room: Kitchen
# @Alias: Kitchen Motion Sensor / Motion Detected / Switch On Kitchen Lights
######################################################################################################
- id: 'KitchenMotionSensorMotionDetectedSwitchOnKitchenLights'
  alias: Kitchen Motion Sensor / Motion Detected / Switch On Kitchen Lights

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0003ce12be
    from: 'off'
    to: 'on'
  
  #condition
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  
  #action
  action:
  - service: light.turn_on
    entity_id: 
      - light.kitchen_lamp
    

######################################################################################################
# @Automation
# @Room: Kitchen
# @Alias: Kitchen Motion Sensor / Motion Detected / Switch On Kitchen Lamp
######################################################################################################
- id: 'KitchenMotionSensorMotionNotDetectedSwitchOffKitchenLights'
  alias: Kitchen Motion Sensor / Motion Not Detected / Switch Off Kitchen Lights

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0003ce12be
    from: 'on'
    to: 'off'
  
  #condition
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  
  #action
  action:
  - service: light.turn_off
    entity_id: 
      - light.kitchen_lamp