######################################################################################################
# @Automation
# @Alias: Home Assistant / Companion App / IOS / iPad / Location / Update / 5
# @Device: iPad 6th Generation
# @Device_URL: https://support.apple.com/kb/sp774?locale=en_MT
# @Trigger:
#  - Time Pattern / 5 mins
# @Condition
#  - After / home_assistant_companion_app_ios_after / 06:00
#  - Before / home_assistant_companion_app_ios_before / 22:00
# @Action:
#  - Update Location
######################################################################################################
- id: 'HomeAssistantCompanionAppIOSiPadLocationUpdate5'
  alias: Home Assistant / Companion App / IOS / iPad / Location / Update / 5
  description: 'Update iPad Location for Battery Stats every 5 minutes'
  
  # trigger
  trigger:
    - platform: time_pattern
      minutes: '/5'

  # condition
  condition:
    - condition: time
      after: !secret home_assistant_companion_app_ios_after
      before: !secret home_assistant_companion_app_ios_before
  
  # action
  action:
    - service: notify.mobile_app_marks_ipad
      data:
        message: "request_location_update"

######################################################################################################
# @Automation
# @Alias: Home Assistant / Companion App / IOS / iPad / Location / Update / 30
# @Device: iPad 6th Generation
# @Device_URL: https://support.apple.com/kb/sp774?locale=en_MT
# @Trigger:
#  - Time Pattern / 30 mins
# @Condition
#  - After / home_assistant_companion_app_ios_after / 06:00
#  - Before / home_assistant_companion_app_ios_before / 22:00
# @Action:
#  - Update Location
######################################################################################################
- id: 'HomeAssistantCompanionAppIOSiPadLocationUpdate30'
  alias: Home Assistant / Companion App / IOS / iPad / Location / Update / 30
  description: 'Update iPad Location for Battery Stats every 5 minutes'
  
  # trigger
  trigger:
    - platform: time_pattern
      minutes: '/30'
  
  # condition
  condition:
    - condition: time
      after: !secret home_assistant_companion_app_ios_after
      before: !secret home_assistant_companion_app_ios_before
  
  # action
  action:
    - service: notify.mobile_app_marks_ipad
      data:
        message: "request_location_update"

######################################################################################################
# @Automation
# @Alias: Home Assistant / Companion App / IOS / iPad / Charging / Increase Location Frequency
# @Device: iPad 6th Generation
# @Device_URL: https://support.apple.com/kb/sp774?locale=en_MT
# @Trigger:
#  - Battery State / Charging
# @Action:
#  - Automation / Turn On / HomeAssitantCompanionAppIOSiPadLocationUpdate5
######################################################################################################
- id: 'HomeAssistantCompanionAppIOSiPadChargingIncreaseLocationFrequency'
  alias: Home Assistant / Companion App / IOS / iPad / Charging / Increase Location Frequency
  description: 'Increase Location Frequency When Charging'

  # trigger
  trigger:
    - platform: state
      entity_id: sensor.marks_ipad_battery_state
      to:  "Charging"
    
  # action
  action:
    - service: automation.turn_on
      entity_id: automation.home_assistant_companion_app_ios_ipad_location_update_5
      
######################################################################################################
# @Automation
# @Alias: Home Assistant / Companion App / IOS / iPad / Charging / Decrease Location Frequency
# @Device: iPad 6th Generation
# @Device_URL: https://support.apple.com/kb/sp774?locale=en_MT
# @Trigger:
#  - Battery State / Not Charging
# @Action:
#  - Automation / Turn Off / HomeAssitantCompanionAppIOSiPadLocationUpdate5
######################################################################################################
- id: 'HomeAssistantCompanionAppIOSiPadChargingDecreaseLocationFrequency'
  alias: Home Assistant / Companion App / IOS / iPad / Charging / Decrease Location Frequency
  description: 'Increase Location Frequency When Charging'

  # trigger
  trigger:
    - platform: state
      entity_id: sensor.marks_ipad_battery_state
      to:  "Not Charging"
    
  # action
  action:
    - service: automation.turn_off
      entity_id: automation.home_assistant_companion_app_ios_ipad_location_update_5

######################################################################################################
# @Automation
# @Alias: Home Assistant / Companion App / IOS / iPad / Charging / Complete
# @Device: iPad 6th Generation
# @Device_URL: https://support.apple.com/kb/sp774?locale=en_MT
# @Trigger:
#  - Battery Level / Above / 99
# @Condition:
#  - Battery State / Full
# @Action:
#  - Notify / Living Room Soundbar
######################################################################################################
- id: 'HomeAssistantCompanionAppIOSiPadChargingComplete'
  alias: Home Assistant / Companion App / IOS / iPad / Charging / Complete
  description: 'Notify When Charging Complete'

  # trigger
  trigger:
    - platform: state
      entity_id: sensor.marks_ipad_battery_level
      to: "100"
      for: "00:05:00"

  # condition
  condition:
    - condition: state
      entity_id: sensor.marks_ipad_battery_state
      state:  "Charging"

    - condition: state
      entity_id: "device_tracker.iphone"
      state: "home"
  
  # action
  action:
    - service: script.notify_base_tts
      data:
        title: "The Loft Notification"
        message: "Tablet is fully charged."