######################################################################################################
# @Automation
# @Alias: Home Assitant / Companion App / Android / Realme X2 Pro / Charging / Complete
# @Device: Realme X2 Pro
# @Device_URL: https://www.realme.com/eu/realme-x2-pro
# @Trigger:
#  - State / Battery / 100
# @Condition:
#  - Battery / Charging
#  - Jessica / Home
# @Action:
#  - Script / Notify / TTS
######################################################################################################
- id: 'HomeAssitantCompanionAppAndroidRealmeX2ProChargingComplete'
  alias: Home Assitant / Companion App / Android / Realme X2 Pro / Charging / Complete
  description: 'Notify When Charging Complete'
  
  # trigger
  trigger:
  - platform: state
    entity_id: sensor.rmx1931_battery_level
    to: '100'

  # condition
  condition:
  - condition: state
    entity_id: sensor.rmx1931_battery_state
    state:  "full"

  - condition: state
    entity_id: "device_tracker.jessica_cilia"
    state: "home"
  
  # action
  action:
  - service: script.notify_base_living_soundbar
    data:
      title: "The Loft Notification"
      message: "Jessica your phone is fully charged."
  - service: script.notify_base_tv
    data:
      title: "The Loft Notification"
      message: "Jessica your phone is fully charged."