######################################################################################################
# @Automation
# @Alias: Home Assistant / Health Check / Media Availability / Alert
# @Device: Sonos Beam
# @Device_URL: https://www.sonos.com/en/shop/beam.html
# @Device: Nest Hub Max
# @Device_URL: https://store.google.com/gb/product/google_nest_hub_max?hl=en-GB
# @Device: Nest Wifi
# @Device_URL: https://store.google.com/gb/product/nest_wifi?hl=en-GB
# @Device: Google Mini
# @Device_URL: https://store.google.com/gb/category/audio_entertainment_systems?hl=en-GB
# @Trigger:
#  - Time / 10:00:00
#  - State / Binary Sensor / Media Availability Sensor / On
# @Condition:
#  - Time / 09:00:00 / 22:00:00
#  - State / Binary Sensor / Media Availability Sensor / On
# @Action:
#  - Notify / Mark
######################################################################################################
- id: 'HomeAssistantHealthCheckMediaAvailabilityAlert'
  alias: Home Assistant / Health Check / Media Availability / Alert

  #trigger
  trigger:
    - platform: time
      at: !secret health_check_daily_run_time

    - platform: state
      entity_id: binary_sensor.media_availability_sensor
      to: 'on'
      for:
        minutes: 30
  
  # condition
  condition:
    - condition: time
      after: !secret health_check_alert_after
      before: !secret health_check_alert_before

    - condition: state
      entity_id: binary_sensor.media_availability_sensor
      state: 'on'
  
  #action
  action:
    - service: script.notify_base_app_mark
      data:
        title: "The Loft Alert"
        message: "Health Check Failure! {{ state_attr('binary_sensor.media_availability_sensor', 'message') }}"