routine_doors_windows:
  alias: Routine / Doors and Windows
  sequence:
  - service: script.doors_windows_check
  - condition: state
    entity_id: binary_sensor.doors_windows_sensors
    state: "off" 
  - service: script.notify_base_living_soundbar
    data:
      title: "The Loft Notification"
      message: "All doors and windows closed"