routine_submarine_mode:
  alias: Routine / Submarine Mode / On
  sequence:
  
  # disable automations (hall and library)
  - service: input_boolean.turn_on
    entity_id:
      - input_boolean.hall_automation_override
      - input_boolean.library_automation_override
      - input_boolean.kitchen_automation_override

  # switch on lights (bedroom bulb, hall and kitchen light)
  - service: light.turn_on
    entity_id:
      - light.bedroom_bulb_1
      - light.hall_bulb
      - light.kitchen_lamp

  - service: switch.turn_on
    data:
      entity_id: switch.living_room_bulb_1_socket_1

routine_submarine_mode_off:
  alias: Routine / Submarine Mode / On
  sequence:
  # enable automations (hall, library and kitchen)
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.hall_automation_override
      - input_boolean.library_automation_override
      - input_boolean.kitchen_automation_override

  # switch on lights (bedroom bulb, hall and kitchen light)
  - service: light.turn_off
    entity_id:
      - light.hall_bulb
      - light.kitchen_lamp

  - service: switch.turn_off
    data:
      entity_id: switch.living_room_bulb_1_socket_1