routine_night:
  alias: Routine / Good Night
  sequence:
  - service: input_boolean.turn_on
    entity_id: input_boolean.night_mode
  - service: script.turn_on
    entity_id:
      - script.doors_windows_check
      - script.room_living_room_off
      - script.room_office_off
      - script.turn_off_rack_room_lights
      - script.turn_off_main_staircase_lights
      - script.turn_on_hall_light
      - script.turn_on_bedroom_lights
  - delay: "00:04:00"  
  - service: script.turn_off_kitchen_devices
  mode: single