routine_living_room_tv_go_interactive_tsn_1:
  alias: Routine / Living Room / TV / GO Interactive / TSN 1
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 1

routine_living_room_tv_go_interactive_tsn_2:
  alias: Routine / Living Room / TV / GO Interactive / TSN 2
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 2
        
routine_living_room_tv_go_interactive_tsn_3:
  alias: Routine / Living Room / TV / GO Interactive / TSN 3
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 3
        
routine_living_room_tv_go_interactive_tsn_4:
  alias: Routine / Living Room / TV / GO Interactive / TSN 4
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 4

routine_living_room_tv_go_interactive_tsn_5:
  alias: Routine / Living Room / TV / GO Interactive / TSN 5
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 5
  
routine_living_room_tv_go_interactive_tsn_6:
  alias: Routine / Living Room / TV / GO Interactive / TSN 6
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 5
        - 6

routine_living_room_tv_go_interactive_tvm:
  alias: Routine / Living Room / TV / GO Interactive / TVM
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 0
        - 1

routine_living_room_tv_go_interactive_net:
  alias: Routine / Living Room / TV / GO Interactive / NET
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 0
        - 2

routine_living_room_tv_go_interactive_one:
  alias: Routine / Living Room / TV / GO Interactive / ONE
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 0
        - 3

routine_living_room_tv_go_interactive_tvm_2:
  alias: Routine / Living Room / TV / GO Interactive / TVM 2
  sequence:
  - service: script.living_room_tv_go_interactive
  - service: remote.send_command
    data:
      entity_id: remote.living_room_rm_pro_remote
      device: GO Interactive
      command:
        - 1
        - 0
        - 4