routine_night:
  alias: Routine / Good Night
  sequence:

  # turn on kitchen, living room and hall light
  - service: light.turn_on
    entity_id: 
      - light.kitchen_bulb_1
      - light.kitchen_bulb_2
      - light.xiaomi_philips_smart_led_bulb
      - light.living_room_lights
      - light.hall_bulb
      - light.bedroom_bulb_1
      - light.bedroom_bulb_2
  
  # check doors and windows
  - service: script.turn_on
    entity_id: script.doors_windows_check

  # turn off air conditioners
  - service: climate.turn_off
    entity_id:
      - climate.office_ac
      - climate.kitchen_ac
      - climate.living_room_ac
  
  # turn off media
  - service: media_player.turn_off
    entity_id:
      - media_player.living_room_tv
      - media_player.kitchen_display
      - media_player.bedroom_wifi
      - media_player.roof_speaker
  
  # turn off lights
  - service: light.turn_off
    entity_id: 
      - light.rack_room_bulb_1
      - light.rack_room_bulb_2
      - light.rack_room_bulb_3
      - light.mainstaircase_bulb_1
      - light.mainstaircase_bulb_2
      - light.office_light_1
      - light.office_light_2
  
  # turn off smart plugs
  - service: switch.turn_off
    entity_id:
      - switch.72627180bcddc292737e
      - switch.bedroom_bulb_3
  
  # delay
  - delay: "00:04:00"

  # turn off / living room
  - service: light.turn_off
    entity_id: 
      - light.living_room_lights
      
  # delay
  - delay: "00:08:00"

  # turn off / kitchen
  - service: light.turn_off
    entity_id: 
      - light.kitchen_bulb_1
      - light.kitchen_bulb_2
      - light.xiaomi_philips_smart_led_bulb

  # turn on night boolean
  - service: input_boolean.turn_on
    entity_id: input_boolean.night_mode

  mode: single