routine_living_room_tv_iptv_e:
  alias: Routine / Living Room / TV / IPTV / E
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"

routine_living_room_tv_iptv_food_network:
  alias: Routine / Living Room / TV / IPTV / Food Network
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "5"

routine_living_room_tv_iptv_history_channel:
  alias: Routine / Living Room / TV / IPTV / History Channel
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "9"

routine_living_room_tv_iptv_sky_sports_news:
  alias: Routine / Living Room / TV / IPTV / Sky Sports News
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"

routine_living_room_tv_iptv_sky_sports_main_event:
  alias: Routine / Living Room / TV / IPTV / Sky Sports Main Event
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "2"

routine_living_room_tv_iptv_sky_sports_football:
  alias: Routine / Living Room / TV / IPTV / Sky Sports Football
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "3"

routine_living_room_tv_iptv_sky_sports_pl:
  alias: Routine / Living Room / TV / IPTV / Sky Sports Premier League
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "4"

routine_living_room_tv_iptv_bt_sport_1:
  alias: Routine / Living Room / TV / IPTV / BT Sport 1
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "6"

routine_living_room_tv_iptv_bt_sport_2:
  alias: Routine / Living Room / TV / IPTV / BT Sport 2
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "7"

routine_living_room_tv_iptv_bt_sport_3:
  alias: Routine / Living Room / TV / IPTV / BT Sport 3
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "8"

routine_living_room_tv_iptv_mutv:
  alias: Routine / Living Room / TV / IPTV / MUTV
  sequence:
  - service: script.living_room_tv_iptv
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "2"
  - service: webostv.button
    data:
      entity_id: media_player.living_room_tv
      button: "1"

