######################################################################################################
# @Automation
# @Alias: Alias
# @Device: Synology DS218+
# @Device_URL: https://www.synology.com/en-global/products/DS218
# @Trigger:
#  - Home Assistant Start
# @Action:
#  - Switch Off / All / Lights
#  - Script / Off / Kitchen Devices
#  - Script / Off / Living Room
#  - Script / Off / Rack Room Lights
#  - Script / Off / Hall Light 
#  - Script / Off / Mainstaircase Lights 
#  - Script / Notify / App / Not Home
######################################################################################################
- id: 'HomeAssistantStartSwitchOffRooms'
  alias: Home Assistant / Start / Switch Off Rooms / Notify
  description: "Switches Off Lights and Devices on HA Start. This is to safeguard against lights being switched on when power is restored post a power cut."
  
  # trigger
  trigger:
  - event: start
    platform: homeassistant
  
  #action
  action:
  - delay: 00:02:00
  - service: script.turn_off_kitchen_devices
  - service: script.room_living_room_off
  - service: script.turn_off_rack_room_lights
  - service: script.turn_off_bedroom_lights
  - service: script.turn_off_hall_light
  - service: script.turn_off_main_staircase_lights
  - service: script.notify_base_app_not_home
    data:
      title: The Loft Notification
      message: Seems that there has been a power outage at the Loft! Power is now restored.