######################################################################################################
# @Automation
# @Alias: Alias
# @Device: Synology DS218+
# @Device_URL: https://www.synology.com/en-global/products/DS218
# @Trigger:
#  - Home Assistant / Start
# @Action:
#  - Automation / Off / ios_iphone_location_update_5
#  - Automation / Off / ios_ipad_location_update_5
#  - Choose / Maintenance Mode / Off
#  - Choose / True / Notify / Base App
#  - Choose / Delay / 2 Minutes
#  - Choose / Switch Off Bulbs
######################################################################################################
- id: 'HomeAssistantStart'
  alias: Home Assistant / Start
  description: "Turns off certain automations."
  
  # trigger
  trigger:
  - event: start
    platform: homeassistant
  
  #action
  action:
  - service: automation.turn_off
    entity_id: 
      - automation.home_assistant_companion_app_ios_ipad_location_update_5
      - automation.home_assistant_companion_app_ios_iphone_location_update_5
  - choose:
    # IF Maintenance Mode Off
    - conditions:
        - condition: state
          entity_id: input_boolean.maintenance_mode
          state: 'off'
      # Notify and Turn Off All lights (Apart From Smart Switches)   
      sequence:
        - delay: 00:05:00
        - service: script.notify_base_app
          data:
            title: "The Loft Alert."
            message: "Looks like there was a Power Failure! Power is now restored."

        - service:  light.turn_off
          data:
            entity_id: 
              - light.kitchen_bulb_1
              - light.kitchen_bulb_2
              - light.dining_room_lights
              - light.dining_room_lights_2
              - light.living_room_lights
              - light.xiaomi_philips_smart_led_bulb
              - light.hall_bulb
              - light.bedroom_bulb_1
              - light.bedroom_bulb_2
              - light.mainstaircase_bulb_1
              - light.mainstaircase_bulb_2
              - light.office_light_1
              - light.office_light_2
              - light.rack_room_bulb_1
              - light.rack_room_bulb_2
              - light.rack_room_bulb_3
              - light.philips_ltg002_07a6cd08_level_light_color_on_off
              - light.philips_ltg002_ce567909_level_light_color_on_off
              - light.philips_ltg002_0e63c908_level_light_color_on_off
              - light.philips_ltg002_f2c87209_level_light_color_on_off
              - light.philips_ltg002_3fb26c09_level_light_color_on_off
              - light.philips_ltg002_ae417109_level_light_color_on_off