######################################################################################################
# @Automation
# @Alias: Home Assistant / Start
######################################################################################################
- id: 'HomeAssistantStart'
  alias: Home Assistant / Start
  description: "Turns off certain automations."
  
  # trigger
  trigger:
  - event: start
    platform: homeassistant
  
  #action
  action:
  - service: automation.turn_off
    entity_id: 
      - automation.home_assistant_companion_app_ios_ipad_location_update_5
      - automation.home_assistant_companion_app_ios_iphone_location_update_5