######################################################################################################
# @Automation
# @Alias: Home Assistant / Maitenance Mode
# @Trigger:
#  - Maitenance Mode / On / 60 Minutes
# @Action:
#  - Maitenance Mode / Off
######################################################################################################
- id: 'HomeAssistantMaitenanceMode'
  alias: Home Assistant / Maitenance Mode
  description: "Turns off Maitenance Mode if left switched on for more then 60 minutes."
  
  # trigger
  trigger:
    - platform: state
      entity_id: input_boolean.maintenance_mode
      to: "on"
      for: 
        minutes: 60

  action:
    # turn off maitenance boolean
    - service: input_boolean.turn_off
      entity_id: input_boolean.maintenance_mode