######################################################################################################
# @Automation
# @Alias: Alias
# @Device: Synology DS218+
# @Device_URL: https://www.synology.com/en-global/products/DS218
# @Trigger:
#  - Home Assistant / Start
# @Action:
#  - Automation / Off / ios_iphone_location_update_5
#  - Automation / Off / ios_ipad_location_update_5
######################################################################################################
- id: 'HomeAssistantStart'
  alias: Home Assistant / Start
  description: "Turns off certain automations."
  
  # trigger
  trigger:
  - event: start
    platform: homeassistant
  
  #action
  action:
  - service: automation.turn_off
    entity_id: 
      - automation.ios_iphone_location_update_5
      - automation.ios_ipad_location_update_5