######################################################################################################
# @Automation
# @Alias: Library Lights / On / Set Color
######################################################################################################
- id: 'LibraryLightsOnSetColor'
  alias: Library Lights / On / Set Color
  description: 'Adjust Lights Color'

  #trigger
  trigger:
    - platform: state
      entity_id:
        - light.philips_ltg002_07a6cd08_level_light_color_on_off
        - light.philips_ltg002_ce567909_level_light_color_on_off
        - light.philips_ltg002_0e63c908_level_light_color_on_off
        - light.philips_ltg002_f2c87209_level_light_color_on_off
        - light.philips_ltg002_3fb26c09_level_light_color_on_off
        - light.philips_ltg002_ae417109_level_light_color_on_off
      from: 'off'
      to: 'on'

  #action
  action:
    - alias: 'Set Light and Dim Lights if Dimmed Mode is On'
      choose:
        # IF Dimmed Mode is On
        conditions:
          - condition: state
            entity_id: input_boolean.dimmed_mode
            state: 'on'

        # Set Library Bulbs in Dimmed Mode
        sequence:
          - service: light.turn_on
            target:
              entity_id: '{{ trigger.entity_id }}'
            data:
              brightness: 60
              color_temp: 345

      default:
        # Set Library Bulbs in Non Dimmed Mode
        - service: light.turn_on
          target:
            entity_id: '{{ trigger.entity_id }}'
          data:
            brightness: 255
            color_temp: 345

  mode: parallel
######################################################################################################
# @Automation
# @Alias: Library Lights / Power Failure / Off
######################################################################################################
# - id: 'LibraryLightsPowerFailureOff'
#   alias: Library Lights / Power Failure / Off
#   description: 'Switch Off Library Bulbs post a Power Failure'

#   #trigger
#   trigger:
#     - platform: state
#       entity_id:
#         - light.philips_ltg002_07a6cd08_level_light_color_on_off
#         - light.philips_ltg002_ce567909_level_light_color_on_off
#         - light.philips_ltg002_0e63c908_level_light_color_on_off
#         - light.philips_ltg002_f2c87209_level_light_color_on_off
#         - light.philips_ltg002_3fb26c09_level_light_color_on_off
#         - light.philips_ltg002_ae417109_level_light_color_on_off
#       from: 'unavailable'
#       to: 'on'

#   #action
#   action:
#     - service: light.turn_off
#       entity_id: '{{ trigger.entity_id }}'

#   mode: parallel
