######################################################################################################
# @Automation
# @Room: Library
# @Alias: Library Lights / On / Set Color
# @Device: Philips Hue White Ambience (GU10)
# @Device_URL: https://www.philips-hue.com/en-us/p/hue-white-ambiance-2-pack-gu10/046677542405
# @Trigger:
#  - Library Lights (x3) / On
# @Action:
#  - Set Library Light Color
######################################################################################################
- id: "LibraryLightsOnSetColor"
  alias: Library Lights / On / Set Color
  description: "Adjust Lights Color"

  #trigger
  trigger:
    - platform: state
      entity_id:
        - light.philips_ltg002_07a6cd08_level_light_color_on_off
        - light.philips_ltg002_ce567909_level_light_color_on_off
        - light.philips_ltg002_0e63c908_level_light_color_on_off
        - light.philips_ltg002_f2c87209_level_light_color_on_off
        - light.philips_ltg002_3fb26c09_level_light_color_on_off
        - light.philips_ltg002_ae417109_level_light_color_on_off
      from: "off"
      to: "on"

  #action
  action:
    - alias: "Set Light and Dim Lights if Night Mode On"
      choose:
        # IF Night Mode On
        - conditions:
            - condition: state
              entity_id: input_boolean.night_mode
              state: "on"
          # Set Library Bulbs in Dimmed Mode
          sequence:
            - service: light.turn_on
              target:
                entity_id: "{{ trigger.entity_id }}"
              data:
                brightness: 170
                color_temp: 345
      default:
        # Set Library Bulbs in Non Dimmed Mode
        - service: light.turn_on
          target:
            entity_id: "{{ trigger.entity_id }}"
          data:
            brightness: 255
            color_temp: 345
  mode: parallel