######################################################################################################
# @Automation
# @Room: Library
# @Alias: Library Motion Sensor 1 / Motion Detected / Switch On Library
# @Device: Philips Hue White Ambience (GU10)
# @Device_URL: https://www.philips-hue.com/en-us/p/hue-white-ambiance-2-pack-gu10/046677542405
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Detected
# @Condition:
#  - 08:00 / 16:00
#  - Library Automation Override / Off
# @Action:
#  - Library Lights (x3) / On
######################################################################################################
- id: 'LibraryMotionSensor1MotionDetectedSwitchOnLibrary'
  alias: Library Motion Sensor 1 / Motion Detected / Switch On Library

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone
    from: 'off'
    to: 'on'

  #condition
  condition:
  - condition: time
    before: !secret light_condition_before
    after: !secret light_condition_after
  - condition: state
    entity_id: input_boolean.library_automation_override
    state: 'off'

  #action
  action:
  - service: light.turn_on
    target:
      entity_id: light.philips_ltg002_07a6cd08_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_on
    target:
      entity_id: light.philips_ltg002_0e63c908_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_on
    target:
      entity_id: light.philips_ltg002_3fb26c09_level_light_color_on_off

######################################################################################################
# @Automation
# @Room: Library
# @Alias: Library Motion Sensor 1 / Motion Not Detected / Switch Off Library
# @Device: Philips Hue White Ambience (GU10)
# @Device_URL: https://www.philips-hue.com/en-us/p/hue-white-ambiance-2-pack-gu10/046677542405
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Not Detected
# @Condition
#  - Library Automation Override / Off
# @Action:
#  - Library Lights (x3) / Off
#  - Delay (300ms)
######################################################################################################
- id: 'LibraryMotionSensor1MotionNotDetectedSwitchOnLibrary'
  alias: Library Motion Sensor 1 / Motion Not Detected / Switch Off Library

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone
    from: 'on'
    to: 'off'

  #condition
  condition:
  - condition: state
    entity_id: input_boolean.library_automation_override
    state: 'off'

  #action
  action:
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_07a6cd08_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_ce567909_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_0e63c908_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_f2c87209_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_3fb26c09_level_light_color_on_off
  - delay:
      milliseconds: 300
  - service: light.turn_off
    target:
      entity_id: light.philips_ltg002_ae417109_level_light_color_on_off