######################################################################################################
# @Automation
# @Room: Library
# @Alias: Library Motion Sensor 1 / Motion Detected
######################################################################################################
- id: 'LibraryMotionSensor1MotionDetected'
  alias: Library Motion Sensor 1 / Motion Detected

  #trigger
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone
      from: 'off'
      to: 'on'

  #condition
  condition:
    # Check for Time Schedule or Time Automation Override Input Boolean
    - condition: or
      conditions:
        - condition: time
          before: input_datetime.light_schedule_time_before
          after: input_datetime.light_schedule_time_after
        - condition: state
          entity_id: input_boolean.light_schedule_time_automation_override
          state: 'on'

    # Check for Library Automation Override Input Boolean
    - condition: state
      entity_id: input_boolean.library_automation_override
      state: 'off'

    # Check for Night Mode Input Boolean
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'

    #Check for Last Trigger for Motion Sensor 2 Automation
    - condition: template
      value_template: >
        {{(as_timestamp(now()) - as_timestamp(states.automation.library_motion_sensor_2_motion_detected.attributes.last_triggered | default(0)) | int > 5)}}

    - condition: state
      entity_id: group.library_lights_2
      state: 'off'

  #action
  action:
    - service: light.turn_on
      target:
        entity_id: light.philips_ltg002_07a6cd08_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_on
      target:
        entity_id: light.philips_ltg002_0e63c908_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_on
      target:
        entity_id: light.philips_ltg002_3fb26c09_level_light_color_on_off

######################################################################################################
# @Automation
# @Room: Library
# @Alias: Library Motion Sensor 1 / Motion Not Detected
######################################################################################################
- id: 'LibraryMotionSensor1MotionNotDetected'
  alias: Library Motion Sensor 1 / Motion Not Detected

  #trigger
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone
      from: 'on'
      to: 'off'

  #condition
  condition:
    - condition: state
      entity_id: input_boolean.library_automation_override
      state: 'off'

  #action
  action:
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_07a6cd08_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_ce567909_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_0e63c908_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_f2c87209_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_3fb26c09_level_light_color_on_off
    - delay:
        milliseconds: 300
    - service: light.turn_off
      target:
        entity_id: light.philips_ltg002_ae417109_level_light_color_on_off
