######################################################################################################
# @Automation
# @Room: Balcony
# @Alias: Balcony / LED Light Strip / On
# @Device: Sonoff L1 Smart Strip light
# @Device_URL: https://sonoff.tech/product/wifi-smart-lighting/l1-smart-strip-light
# @Trigger:
#  - Time / 17:30:00
# @Action:
#  - LED Light Strip / On
######################################################################################################
- id: 'BalconyLEDLightStripOn'
  alias: Balcony / LED Light Strip / On
  description: 'Turns LED Light Strip on at Set Interval'
  
  # trigger
  trigger:
  - platform: time
    at: "17:00:00"
  
  # action
  action:
  - service: switch.turn_on
    entity_id: switch.bedroom_bulb_3_socket_1

######################################################################################################
# @Automation
# @Room: Balcony
# @Alias: Balcony / LED Light Strip / Off
# @Device: Sonoff L1 Smart Strip light
# @Device_URL: https://sonoff.tech/product/wifi-smart-lighting/l1-smart-strip-light
# @Trigger:
#  - Time / 23:30:00
# @Action:
#  - LED Light Strip / Off
######################################################################################################
- id: 'BalconyLEDLightStripOff'
  alias: Balcony / LED Light Strip / Off

  #trigger
  trigger:
  - platform: time
    at: "23:59:00"
  
  # action
  action:
  - service: switch.turn_off
    entity_id: switch.bedroom_bulb_3_socket_1