######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / On / 6:00
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Time / 06:00:00
# @Action:
#  - Water Heater / On
######################################################################################################
- id: 'ShowerWaterHeaterOn600'
  alias: Shower / Water Heater / On / 6:00
  description: 'Switch On Water Heater at Set Intervals'

  #trigger
  trigger:
  - platform: time
    at: "06:00:00"
  
  #action
  action:
  - service: switch.turn_on
    entity_id: switch.spare_bathroom_water_heater_sw

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / On / 17:00
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Time / 16:00:00
# @Action:
#  - Water Heater / On
######################################################################################################
- id: 'ShowerWaterHeaterOn1600'
  alias: Shower / Water Heater / On / 16:00
  description: 'Switch On Water Heater at Set Intervals'

  #trigger
  trigger:
  - platform: time
    at: "16:00:00"
  
  #action
  action:
  - service: switch.turn_on
    entity_id: switch.spare_bathroom_water_heater_sw

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / Off / 90
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Switch / On / 90 mins
# @Action:
#  - Water Heater / Off
######################################################################################################
- id: 'ShowerWaterHeaterOff90'
  alias: Shower / Water Heater / Off / 90
  description: 'Switch Off Water Heater after switched off for 90mins'

  #trigger
  trigger:
  - platform: state
    entity_id: switch.spare_bathroom_water_heater_sw
    from: 'off'
    to: 'on'
    for: 
      minutes: '90'

  #action
  action:
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - service: script.notify_base_tts
    data:
      title: "The Loft Notification"
      message: "Shower Water Heater is Warm. Water Heater is now switched off."

######################################################################################################
# @Automation
# @Room: Shower
# @Alias: Shower / Water Heater / Off / 60
# @Device: Shelly 1pm
# @Device_URL: https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/
# @Trigger:
#  - Switch / On / 60 mins
# @Action:
#  - Water Heater / Off
######################################################################################################
- id: 'ShowerWaterHeaterOff60'
  alias: Shower / Water Heater / Off / 60
  description: 'Switch Off Water Heater after switched off for 60mins'

  #trigger
  trigger:
  - platform: state
    entity_id: switch.spare_bathroom_water_heater_sw
    from: 'off'
    to: 'on'
    for: 
      minutes: '60'

  #action
  action:
  - service: switch.turn_off
    entity_id: switch.spare_bathroom_water_heater_sw
  - service: script.notify_base_tts
    data:
      title: "The Loft Notification"
      message: "Shower Water Heater is Warm. Water Heater is now switched off."
