######################################################################################################
# @Automation
# @Alias: Jessica / Phone / Charging / Complete
# @Device: Realme X2 Pro
# @Device_URL: https://www.realme.com/eu/realme-x2-pro
# @Trigger:
#  - State / Battery / 100
# @Condition:
#  - Battery / Charging
# @Action:
#  - Script / Notify / TTS
######################################################################################################
- id: 'JessicaPhoneChargingComplete'
  alias: Jesscia / Phone / Charging / Complete
  description: 'Notify When Charging Complete'
  
  # trigger
  trigger:
  - platform: state
    entity_id: sensor.rmx1931_battery_level
    to: '100'

  # condition
  condition:
  - condition: state
    entity_id: sensor.rmx1931_battery_state
    state:  "charging"
  
  # action
  action:
  - service: script.notify_base_tts
    data:
      title: "The Loft Alert"
      message: "Madam Jessica. Your phone is fully charged."
