#################################################################
## Automations / Room / Kitchen / Aqara Cube
#################################################################

- id: '1586063239458'
  alias: 'Kitchen Cube / Tap Twice / Turn Off All Kitchen Devices'
  description: ''
  trigger:
  - event_data:
      action_type: tap_twice
      entity_id: binary_sensor.kitchen_cube
    event_type: xiaomi_aqara.cube_action
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: climate.kitchen_ac
    service: climate.turn_off
  - data: {}
    entity_id: climate.living_room_ac
    service: climate.turn_off
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_off
  - data: {}
    entity_id: light.kitchen_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.kitchen_bulb_2
    service: light.turn_off
  - data: {}
    entity_id: switch.72627180bcddc292737e
    service: switch.turn_off
- id: '1586102383951'
  alias: Kitchen Cube / Shake / Toggle Kitchen Lights
  description: ''
  trigger:
  - event_data:
      action_type: shake_air
      entity_id: binary_sensor.kitchen_cube
    event_type: xiaomi_aqara.cube_action
    platform: event
  condition: []
  action:
  - entity_id: light.kitchen_bulb_1
    service: light.toggle
  - entity_id: light.kitchen_bulb_2
    service: light.toggle
- id: '1588362214269'
  alias: Hall Motion Sensor / On / Switch On Hall
  description: ''
  trigger:
  - entity_id: binary_sensor.hall_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '16:00'
    before: 08:00
    condition: time
  action:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_on
- id: '1588362959895'
  alias: Hall Motion Sensor / Off / Switch Off Hall
  description: ''
  trigger:
  - entity_id: binary_sensor.hall_motion_sensor
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_off
- id: '1588524093414'
  alias: Rack Room Sensor / On / Switch on Rack Room
  description: ''
  trigger:
  - entity_id: binary_sensor.rack_room_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.rack_room_bulb_1
    service: light.turn_on
  - data: {}
    entity_id: light.rack_room_bulb_2
    service: light.turn_on
  - data: {}
    entity_id: light.rack_room_bulb_3
    service: light.turn_on
- id: '1588524190098'
  alias: Rack Room Sensor / Off / Switch off Rack Room
  description: ''
  trigger:
  - entity_id: binary_sensor.rack_room_sensor
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.rack_room_bulb_1
    service: light.turn_off
  - data: {}
    entity_id: light.rack_room_bulb_2
    service: light.turn_off
  - data: {}
    entity_id: light.rack_room_bulb_3
    service: light.turn_off
- id: '1590853423686'
  alias: Home Assistant / Start / Switch Off Rooms
  description: Power Cut Scenario
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02:00
  - data: {}
    service: script.turn_off_kitchen_devices
  - service: script.room_living_room_off
    data: {}
  - data: {}
    service: script.turn_off_rack_room_lights
  - data: {}
    service: script.turn_off_bedroom_lights
  - data: {}
    service: script.turn_off_hall_light
  - data: {}
    service: script.turn_off_main_staircase_lights
  mode: single
- id: '1591958664344'
  alias: Kitchen AC / Living Room Door / Alert 1
  description: Alerts if Living Room Door is Open whilst trying to switch on Kitchen
    Air Conditioner.
  trigger:
  - platform: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  action:
  - delay: 0:02
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - data:
      message: Close Living Room Door for Kitchen AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.living_room_tv
  - data:
      message: Close Living Room Door for Kitchen AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.mobile_app_the_loft_ha_wifi
  - data:
      gw_mac: 7C:49:EB:1C:F2:2F
      ringtone_id: 12
    service: xiaomi_aqara.play_ringtone
  - delay: 0:02
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - data: {}
    entity_id: climate.kitchen_ac
    service: climate.turn_off
  - data:
      message: Living Room Door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.living_room_tv
  - data:
      message: Living Room Door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.mobile_app_the_loft_ha_wifi
- id: '1592124265679'
  alias: Kitchen AC / Living Room Door / Alert 2
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  action:
  - delay: 0:03
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - data:
      gw_mac: 7C:49:EB:1C:F2:2F
      ringtone_id: 12
    service: xiaomi_aqara.play_ringtone
  - data:
      message: Close living room door for kitchen AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.living_room_tv
  - data:
      message: Close living room door for kitchen AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.mobile_app_the_loft_ha_wifi
  - delay: 0:02
  - condition: template
    value_template: '{{ (is_state(''climate.kitchen_ac'', ''off'') == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - data: {}
    entity_id: climate.kitchen_ac
    service: climate.turn_off
  - data:
      message: Living room door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.living_room_tv
  - data:
      message: Living room door still open. Kitchen AC has been switched off.
      title: 'Alert: Kitchen AC Switched Off.'
    service: notify.mobile_app_the_loft_ha_wifi
- id: '1591958664345'
  alias: Living Room AC / Living Room Door / Alert 1
  description: Alerts if Living Room Door is open whilst trying to switch on Living
    Room Air Conditioner.
  trigger:
  - platform: template
    value_template: '{{ (is_state(''climate.living_room_ac'', ''off'') == false) }}'
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  action:
  - delay: 0:02
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.living_room_ac'', ''off'') == false) }}'
  - data:
      message: Close Living Room Door for Living Room AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.living_room_tv
  - data:
      message: Close Living Room Door for Living Room AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.mobile_app_the_loft_ha_wifi
  - data:
      gw_mac: 7C:49:EB:1C:F2:2F
      ringtone_id: 12
    service: xiaomi_aqara.play_ringtone
  - delay: 0:02
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state(''climate.living_room_ac'', ''off'') == false) }}'
  - data: {}
    entity_id: climate.living_room_ac
    service: climate.turn_off
  - data:
      message: Living Room Door still open. Living Room AC has been switched off.
      title: 'Alert: Living Room AC Switched Off.'
    service: notify.living_room_tv
  - data:
      message: Living Room Door still open. Living Room AC has been switched off.
      title: 'Alert: Living Room AC Switched Off.'
    service: notify.mobile_app_the_loft_ha_wifi
- id: '1592124265689'
  alias: Living Room AC / Living Room Door / Alert 2
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ (is_state(''climate.living_room_ac'', ''off'') == false) }}'
  action:
  - delay: 0:03
  - condition: template
    value_template: '{{ (is_state(''living_room_ac'', ''off'') == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - data:
      gw_mac: 7C:49:EB:1C:F2:2F
      ringtone_id: 12
    service: xiaomi_aqara.play_ringtone
  - data:
      message: Close living room door for Living Room AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.living_room_tv
  - data:
      message: Close living room door for Living Room AC to remain switched on.
      title: 'Alert: Living Room Door is Open!'
    service: notify.mobile_app_the_loft_ha_wifi
  - delay: 0:02
  - condition: template
    value_template: '{{ (is_state(''climate.living_room_ac'', ''off'') == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - data: {}
    entity_id: climate.living_room_ac
    service: climate.turn_off
  - data:
      message: Living Room Door still open. Living Room AC has been switched off.
      title: 'Alert: Living Room AC Switched Off.'
    service: notify.living_room_tv
  - data:
      message: Living Room Door still open. Living Room AC has been switched off.
      title: 'Alert: Living Room AC Switched Off.'
    service: notify.mobile_app_the_loft_ha_wifi
- id: '1598358267518'
  alias: Staircase Sensor 1 / Off / Switch Off Staircase
  description: ''
  trigger:
  - entity_id: binary_sensor.staircase_sensor_1
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    service: script.turn_off_main_staircase_lights
- id: '1598358350512'
  alias: Staircase Sensor 1 / On / Switch On Staircase
  description: ''
  trigger:
  - entity_id: binary_sensor.staircase_sensor_1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    service: script.turn_on_main_staircase_lights
- id: '1603541750341'
  alias: Vacuum / Notify / Location Leave
  description: ''
  trigger:
  - platform: state
    entity_id: group.the_loft_members
    from: home
    to: not_home
    for: 0:15
  condition:
  - condition: template
    value_template: '{{ state_attr(''input_datetime.last_vacuum_clean'', ''day'')
      != now().strftime(''%-d'') }}'
  action:
  - service: script.notify_ios_android
    data: {}
  mode: single
- id: '1604158015066'
  alias: 'Vacuum / Helper / Date / Set '
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    attribute: status
    from: Charging
    to: Cleaning
    for: 00:00:02
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
    entity_id: input_datetime.last_vacuum_clean
  mode: single
- id: '1604238557379'
  alias: Vacuum / Notify / Action
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_VACUUM
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: START_VACUUM
  condition: []
  action:
  - service: vacuum.start
    data: {}
    entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single

#################################################################
## Automations
## @Room: Bedroom
## @Devices: Yeelight Lights / Xiaomi Aqara Cube
#################################################################

- id: BedroomCubeShakeAlertToggleBedroomLights
  alias: Bedroom Cube / Shake / Toggle Bedroom Lights
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bedroom_cube
      action_type: shake_air
  action:
  - service: light.toggle
    data:
      entity_id: light.bedroom_bulb_1
      brightness: 50
      transition: 1
  - service: light.toggle
    data:
      entity_id: light.bedroom_bulb_2
      brightness: 50
      transition: 1
  mode: single

- id: BedroomCubeFlip90ToggleBedroomLight1
  alias: Bedroom Cube / Flip90 / Toggle Bedroom Light 1
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bedroom_cube
      action_type: flip90
  action:
  - service: light.toggle
    data:
      entity_id: light.bedroom_bulb_1
      brightness: 50
      transition: 1
  mode: single

- id: BedroomCubeFlip180ToggleBedroomLight2
  alias: Bedroom Cube / Flip180 / Toggle Bedroom Light 2
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bedroom_cube
      action_type: flip180
  action:
  - service: light.toggle
    data:
      entity_id: light.bedroom_bulb_2
      brightness: 50
      transition: 1
  mode: single

- id: BedroomCubeTapTwiceSwitchOffBedroomAndHallLights
  alias: Bedroom Cube / Tap Twice / Switch Off Bedroom and Hall Lights 
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bedroom_cube
      action_type: tap_twice
  action:
  - service: script.turn_off_bedroom_lights
  - service: script.turn_off_hall_light
  mode: single

- id: BedroomCubeRotateBrightnessBedroomLights
  alias: Bedroom Cube / Rotate / Brightness Bedroom Lights 
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bedroom_cube
      action_type: rotate
  action:
  - service: light.turn_on
    data:
      entity_id:
        - light.bedroom_bulb_1
        - light.bedroom_bulb_2
      brightness: >
        {% set state = state_attr('light.bedroom_bulb_1','brightness') -%}
        {%-  if state == None -%}
            {%- set state = 50 -%}
        {%-  elif trigger.event.data.action_value|int > 0 -%}
            {%- set state = state_attr('light.bedroom_bulb_1','brightness') + 100 -%}
        {%-  elif trigger.event.data.action_value|int < 0 -%}
            {%- set state = state_attr('light.bedroom_bulb_1','brightness') - 100 -%}
        {%- endif %}
        {{ state }}
  mode: single

