- platform: template
  sensors:
    door_window_sensors_battery:
      friendly_name: 'Door/Window Sensors / Battery'
      value_template: >-
        {{
          states('sensor.battery_158d0002b771b8')|int < 15 
            or states('sensor.battery_158d0002c628be')|int < 15
            or states('sensor.battery_158d0002b7b84e')|int < 15
        }}

    motion_sensors_battery:
      friendly_name: 'Motion Sensors / Battery'
      value_template: >-
        {{
          states('sensor.battery_158d0001e19483')|int < 15
            or states('sensor.battery_158d00023ec75f')|int < 15
            or states('sensor.battery_158d0002413b7c')|int < 15
            or states('sensor.battery_158d0003ce121b')|int < 15
        }}

    magic_cube_battery:
      friendly_name: 'Magic Cube / Battery'
      value_template: >-
        {{
          states('sensor.battery_158d00028aefda')|int < 15
            or states('sensor.battery_158d00028f8633')|int < 15
        }}
    
    wireless_switch_battery:
      friendly_name: 'Wireless Switch / Battery'
      value_template: >-
        {{
          states('sensor.battery_158d0003e7c53f')|int < 15
        }}