#################################################################
## @climate: living_room_ac
#################################################################
- platform: gree
  name: Living Room AC
  host: !secret gree_living_room_ac_host
  mac: !secret gree_living_room_ac_mac
  target_temp_step: 1
  port: 7000

#################################################################
## @climate: kitchen_ac
#################################################################
- platform: gree
  name: Kitchen AC
  host: !secret gree_kitchen_ac_host
  mac: !secret gree_kitchen_ac_mac
  target_temp_step: 1
  port: 7000
#################################################################
## @climate: office_ac
#################################################################
- platform: gree
  name: Office AC
  host: !secret gree_office_ac_host
  mac: !secret gree_office_ac_mac
  target_temp_step: 1
  port: 7000
