# Thermostasts Settings

- platform: gree
  name: Living Room AC
  host: !secret gree_living_room_ac_host
  mac: !secret gree_living_room_ac_mac
  target_temp_step: 1
  port: 7000

- platform: gree
  name: Kitchen AC
  host: !secret gree_kitchen_ac_host
  mac: !secret gree_kitchen_ac_mac
  target_temp_step: 1
  port: 7000

- platform: gree
  name: Office AC
  host: !secret gree_office_ac_host
  mac: !secret gree_office_ac_mac
  target_temp_step: 1
  port: 7000

  # optional settings:
  # timeout: 10
  # temp_sensor: <temperature sensor in first AC room>
  # xfan: <input_boolean used to switch xfan on/off of your first AC>
  # health: <input_boolean used to switch the Health option on/off of your first AC>
  # sleep: <input_boolean used to switch sleep on/off of your first AC>
  # powersave: <input_boolean used to switch powersave on/off of your first AC>
  # eightdegheat: <input_boolean used to switch 8 degree heating on/off on your first AC>