#################################################################
# @cloud: Google Assistant
#################################################################
google_actions:
  filter:
    exclude_entities:
      - binary_sensor.door_window_sensor_158d0002b771b8
      - binary_sensor.door_window_sensor_158d0002b7b84e
      - binary_sensor.door_window_sensor_158d0002c628be
      - media_player.the_loft_speaker_group
      - media_player.kitchen_display
      - media_player.roof_speaker
      - media_player.bedroom_wifi
      - light.gateway_light_7c49eb1cf22f
      - light.gateway_light_7c49ebb19bf5
      - script.check_back_roof_door_tts
      - script.check_front_roof_door_tts
      - script.check_living_room_door
      - script.notify_ios_android
      - script.room_living_room_lights_off
      - script.room_office_devices_off
      - script.room_office_off
      - script.room_office_lights_off
      - script.turn_off_bedroom_lights
      - script.turn_off_hall_light
      - script.turn_off_kitchen_devices
      - script.turn_off_living_room_devices
      - script.turn_off_main_staircase_lights
      - script.turn_off_rack_room_lights
      - script.turn_on_bedroom_lights
      - script.turn_on_hall_light
      - script.turn_on_lights_office
      - script.turn_on_main_staircase_lights
      - script.room_living_room_off
      - script.notify_base_app
      - script.notify_vacuum_app
    exclude_domains:
      - group
      - binary_sensor
      - camera
      - sensor
      
  entity_config:

    #################################################################
    ## @lights: kitchen
    #################################################################
    light.kitchen_bulb_1:
      name: Kitchen Bulb 1
      room: kitchen
    light.kitchen_bulb_2:
      name: Kitchen Bulb 2
      room: kitchen

    #################################################################
    ## @lights: living room
    #################################################################
    switch.72627180bcddc292737e:
      name: Living Room Bulb 1
      room: living room
    light.living_room_lights:
      name: Living Room Light 1
      aliases:
        - Living Spotlights 1
        - Living Downlights 1
      room: living room

    #################################################################
    ## @lights: dining room
    #################################################################
    light.dining_room_lights:
      name: Dining Room Light 1
      aliases:
        - Dining Spotlights 1
        - Dining Downlights 1
      room: dining room
    light.dining_room_lights_2:
      name: Dining Room Light 2
      room: dining room

    #################################################################
    ## @lights: hall way
    #################################################################
    light.hallway_bulb:
      name: Hall Bulb
      room: hall

    #################################################################
    ## @lights: rack room
    #################################################################
    light.rack_room_bulb_1:
      name: Rack Room Bulb 1
      room: rack room
    light.rack_room_bulb_2:
      name: Rack Room Bulb 2
      room: rack room
    light.rack_room_bulb_3:
      name: Rack Room Bulb 3
      room: rack room
    
    #################################################################
    ## @lights: bedroom
    #################################################################
    light.bedroom_bulb_1:
      name: Bedroom Bulb 1
      room: bedroom
    light.bedroom_bulb_2:
      name: Bedroom Bulb 2
      room: bedroom
    switch.bedroom_bulb_3:
      name: Bedroom Bulb 3
      room: bedroom

    #################################################################
    ## @lights: main staircase
    #################################################################
    light.mainstaircase_bulb_1:
      name: Mainstaircase Bulb 1
      room: main staircase
    light.mainstaircase_bulb_2:
      name: Mainstaircase Bulb 2
      room: main staircase

    #################################################################
    ## @lights: office
    #################################################################
    light.office_light_1:
      name: Office Light 1
      aliases:
        - Office Spot Lights 1
        - Office Downlights 1
      room: office
    light.office_light_2:
      name: Office Light 2
      aliases:
        - Office Spot Lights 2
        - Office Downlights 2
      room: office
    
    #################################################################
    ## @climate: kitchen
    #################################################################
    climate.kitchen_ac:
      name: Kitchen AC
      aliases:
        - Kitchen AC
      room: kitchen
    
    #################################################################
    ## @climate: living room
    #################################################################
    climate.living_room_ac:
      name: Living Room AC
      aliases:
        - Living Room AC
        - Living AC
      room: living room

    #################################################################
    ## @climate: office
    #################################################################
    climate.office_ac:
      name: Office AC
      aliases:
        - Office AC
      room: office

    #################################################################
    ## @media: living room
    #################################################################
    media_player.living_room_tv:
      name: Living Room TV
      aliases:
        - TV
      room: living room

    #################################################################
    ## @vacuum: rack room
    #################################################################
    vacuum.xiaomi_vacuum_cleaner:
      name: Nunu
      room: rack room
      aliases:
        - Vacuum
        - Vacuum Cleaner
        - Nunu
 
    #################################################################
    ## @water-heater: shower
    #################################################################
    switch.spare_bathroom_water_heater_sw:
      name: Shower Water Heater
      aliases: 
        - Shower Water Heater
        - Shower Geyser
      room: shower