################################################################################
## @home: The Loft
## @author: Mark Cilia
## @git: https://github.com/mjcilia/the-loft-ha
################################################################################
default_config:
homeassistant:
  name: The Loft
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  customize: !include customize.yaml

################################################################################
## @includes
################################################################################
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
climate: !include climate.yaml
cloud: !include cloud.yaml
sensor: !include sensors.yaml
logger: !include logger.yaml
discovery: !include discovery.yaml
input_text:
  living_room_soundbar_source:
    name: Living Room Soundbar Source
    initial: TV

################################################################################
## @integrartions
################################################################################

################################################################################
## @integration: Yeelight
## @integration_url: https://www.home-assistant.io/integrations/yeelight/
################################################################################
yeelight: !include yeelight.yaml

################################################################################
## @integration: Xiaomi Miio
## @integration_url: https://www.home-assistant.io/integrations/xiaomi_miio/
################################################################################
vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_miio_vacuum_host
    token: !secret xiaomi_miio_vacuum_token

################################################################################
## @integration: Tuya
## @integration_url: https://www.home-assistant.io/integrations/tuya/
################################################################################
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 356
  platform: smart_life

################################################################################
## @integration: Synology Dsm
## @integration_url: https://www.home-assistant.io/integrations/synology_dsm/
################################################################################  
synology_dsm:
  - host: !secret synology_host
    port: !secret synology_port
    ssl: false
    username: !secret synology_username
    password: !secret synology_password

################################################################################
## @integration: Google Nest
## @integration_url: https://www.home-assistant.io/integrations/nest/
################################################################################ 
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

webostv:
  - name: Living Room TV
    host: !secret webostv_host
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webostv_mac
    customize:
      sources:
        - youtube
        - netflix
        - PS4
        - GO Interactive
        - Plex

wake_on_lan:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_gateway_1_mac
      key: !secret xiaomi_aqara_gateway_1_key
      host: !secret xiaomi_aqara_gateway_1_host
    - mac: !secret xiaomi_aqara_gateway_2_mac
      key: !secret xiaomi_aqara_gateway_2_key
      host: !secret xiaomi_aqara_gateway_2_host
    - mac: !secret xiaomi_aqara_gateway_3_mac
      key: !secret xiaomi_aqara_gateway_3_key
      host: !secret xiaomi_aqara_gateway_3_host

#################################################################
## @notifications
#################################################################
notify:
mobile_app:
ios: !include ios.yaml

#################################################################
## @tts: Text to Speach
#################################################################
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_miio_vacuum_host
    token: !secret xiaomi_miio_vacuum_token
    username: markjcilia@gmail.com
    password: zebbugcilia007
    name: "My Vacuum Camera"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
      6: [243, 156, 18]
      7: [88, 214, 141]
      8: [245, 176, 65]
      9: [252, 212, 81]
      10: [72, 201, 176]
      11: [84, 153, 199]
      12: [133, 193, 233]
      13: [245, 176, 65]
      14: [82, 190, 128]
      15: [72, 201, 176]
      16: [165, 105, 18]
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
      - zones
    texts:
      - text: "Room 1"
        x: 25
        y: 25
        color: [125, 20, 213]
      - text: "Room 2"
        x: 25
        y: 75
        color: [125, 20, 213, 127]
        font: "FreeSans.ttf"
        font_size: 25
    map_transformation:
      scale: 2
      rotate: 180
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true