################################################################################
## @home: The Loft
## @author: Mark Cilia
## @git: https://github.com/mjcilia/the-loft-ha
################################################################################
default_config:
homeassistant:
  name: The Loft
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  customize: !include customize.yaml
  time_zone: Europe/Malta

################################################################################
## @includes
################################################################################
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
cloud: !include cloud.yaml
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include sensors.yaml
logger: !include logger.yaml
discovery: !include discovery.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light.yaml

################################################################################
## @integrations
################################################################################

################################################################################
## @integration: Sonos
## @integration_url: https://www.home-assistant.io/integrations/sonos/
################################################################################
sonos:
  media_player:
    hosts:
      - !secret sonos_living_room_soundbar

################################################################################
## @integration: Sonoff
## @integration_url: https://github.com/AlexxIT/SonoffLAN
################################################################################
#sonoff:
#  username: !secret sonoff_username
#  password: !secret sonoff_password

################################################################################
## @integration: Google Nest
## @integration_url: https://www.home-assistant.io/integrations/nest/
################################################################################ 
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

################################################################################
## @integration: Google Calendar
## @integration_url: https://www.home-assistant.io/integrations/nest/
################################################################################ 
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# webostv:
#   - name: Living Room TV
#     host: !secret webostv_host
#     turn_on_action:
#       service: wake_on_lan.send_magic_packet
#       data:
#         mac: !secret webostv_mac
#     customize:
#       sources:
#         - Plex
#         - youtube
#         - netflix
#         - PS4
#         - Melita
#         - Smart IPTV   

wake_on_lan: # enables `wake_on_lan` integration

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_gateway_1_mac
      key: !secret xiaomi_aqara_gateway_1_key
      host: !secret xiaomi_aqara_gateway_1_host
    - mac: !secret xiaomi_aqara_gateway_2_mac
      key: !secret xiaomi_aqara_gateway_2_key
      host: !secret xiaomi_aqara_gateway_2_host

#################################################################
## @integration: Spotify
## @integration_url: https://www.home-assistant.io/integrations/spotify/
#################################################################
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

################################################################
## @integration: Plant Monitor
## @integration_url: https://www.home-assistant.io/integrations/plant/
#################################################################
plant: !include plant.yaml

#################################################################
## @notifications
#################################################################
notify:
mobile_app:
ios: !include ios.yaml

#################################################################
## @tts: Text to Speach
#################################################################
tts:
  - platform: google_translate
    cache: false
    cache_dir: /tmp/tts