################################################################################
## @home: The Loft
## @author: Mark Cilia
## @git: https://github.com/mjcilia/the-loft-ha
################################################################################
default_config:
homeassistant:
  name: The Loft
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  customize: !include customize.yaml
  time_zone: Europe/Malta

################################################################################
## @includes
################################################################################
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
cloud: !include cloud.yaml
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include sensors.yaml
logger: !include logger.yaml
discovery: !include discovery.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml

################################################################################
## @integrations
################################################################################

################################################################################
## @integration: Yeelight
## @integration_url: https://www.home-assistant.io/integrations/yeelight/
################################################################################
yeelight: !include yeelight.yaml

################################################################################
## @integration: Xiaomi Miio
## @integration_url: https://www.home-assistant.io/integrations/xiaomi_miio/
################################################################################
vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_miio_vacuum_host
    token: !secret xiaomi_miio_vacuum_token

################################################################################
## @integration: Sonoff
## @integration_url: https://github.com/AlexxIT/SonoffLAN
################################################################################
#sonoff:
#  username: !secret sonoff_username
#  password: !secret sonoff_password

################################################################################
## @integration: Synology Dsm
## @integration_url: https://www.home-assistant.io/integrations/synology_dsm/
################################################################################  
synology_dsm:
  - host: !secret synology_host
    port: !secret synology_port
    ssl: false
    username: !secret synology_username
    password: !secret synology_password

################################################################################
## @integration: Google Nest
## @integration_url: https://www.home-assistant.io/integrations/nest/
################################################################################ 
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

################################################################################
## @integration: Google Calendar
## @integration_url: https://www.home-assistant.io/integrations/nest/
################################################################################ 
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

webostv:
  - name: Living Room TV
    host: !secret webostv_host
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webostv_mac
    customize:
      sources:
        - youtube
        - netflix
        - PS4
        - GO Interactive
        - Smart IPTV
        - plex

wake_on_lan:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_gateway_1_mac
      key: !secret xiaomi_aqara_gateway_1_key
      host: !secret xiaomi_aqara_gateway_1_host
    - mac: !secret xiaomi_aqara_gateway_2_mac
      key: !secret xiaomi_aqara_gateway_2_key
      host: !secret xiaomi_aqara_gateway_2_host
    - mac: !secret xiaomi_aqara_gateway_3_mac
      key: !secret xiaomi_aqara_gateway_3_key
      host: !secret xiaomi_aqara_gateway_3_host

#################################################################
## @notifications
#################################################################
notify:
mobile_app:
ios: !include ios.yaml

#################################################################
## @tts: Text to Speach
#################################################################
tts:
  - platform: google_translate
    cache: false
    cache_dir: /tmp/tts