#################################################################
## @Device: Kitchen AC
#################################################################
climate.1e5418e7:
  friendly_name: Kitchen AC

#################################################################
## @Device: Kitchen Lamp
#################################################################
light.xiaomi_philips_smart_led_bulb:
  friendly_name: Kitchen Lamp
  icon: mdi:lightbulb

#################################################################
## @Device: Living Room AC
#################################################################
climate.1e541900:
  friendly_name: Living Room AC

#################################################################
## @Device: Living Room Table Switch
#################################################################
binary_sensor.switch_158d0003e7c53f:
  friendly_name: Living Room Table Switch

sensor.battery_158d0003e7c53f:
  friendly_name: Living Room Table Switch Battery
  
#################################################################
## @Device: Living Room Smart Plug
#################################################################
switch.living_room_bulb_1_socket_1:
  friendly_name: Living Room Bulb 1
  icon: mdi:lightbulb

#################################################################
## @Device: Bedroom Smart Plug
#################################################################
switch.bedroom_bulb_3_socket_1:
  friendly_name: Bedroom Fan
  icon: mdi:fan

#################################################################
## @Device: Living Room Light 1
#################################################################
light.living_room_lights:
  friendly_name: Living Room Light 1

#################################################################
## @Device: Dining Room Light 1
#################################################################
light.dining_room_lights:
  friendly_name: Dining Room Light 1

#################################################################
## @Device: Dining Room Light 2
#################################################################
light.dining_room_lights_2:
  friendly_name: Dining Room Light 2

#################################################################
## @Device: Dining Room Cube
#################################################################
binary_sensor.cube_158d0005d41224:
  friendly_name: Dining Room Cube

sensor.battery_158d0005d41224:
  friendly_name: Dining Room Cube Battery

#################################################################
## @Device: Kitchen Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d0003ce12be:
  friendly_name: Kitchen Motion Sensor

sensor.battery_158d0003ce12be:
  friendly_name: Kitchen Motion Sensor Battery

#################################################################
## @Device: Hall Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d0002413b7c:
  friendly_name: Hall Motion Sensor

sensor.battery_158d0002413b7c:
  friendly_name: Hall Motion Sensor Battery

#################################################################
## @Device: Library Motion Sensor
#################################################################
binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone:
  friendly_name: Library Motion Sensor 1 [ZHA]

sensor.lumi_lumi_sensor_motion_1b12ce03_power:
  friendly_name: Library Motion Sensor 1 [ZHA] Battery

#################################################################
## @Device: Study Motion Sensor (New)
#################################################################
binary_sensor.lumi_lumi_sensor_motion_34464102_ias_zone:
  friendly_name: Study Motion Sensor [ZHA]

sensor.lumi_lumi_sensor_motion_34464102_power:
  friendly_name: Study Motion Sensor [ZHA] Battery

#################################################################
## @Device: Study AC
#################################################################
climate.1ebfaa4e:
  friendly_name: Study AC

#################################################################
## @Device: Rack Room Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d00023ec75f:
  friendly_name: Rack Room Motion Sensor

sensor.battery_158d00023ec75f:
  friendly_name: Rack Room Motion Sensor Battery

#################################################################
## @Device: Staircase Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d0001e19483:
  friendly_name: Staircase Motion Sensor

sensor.battery_158d0001e19483:
  friendly_name: Staircase Motion Sensor 1 Battery

#################################################################
## @Device: Bedroom Cube
#################################################################
binary_sensor.cube_158d00028aefda:
  friendly_name: Bedroom Cube

sensor.battery_158d00028aefda:
  friendly_name: Bedroom Cube Battery

#################################################################
## @Device: Kitchen Cube
#################################################################
binary_sensor.cube_158d00028f8633:
  friendly_name: Kitchen Cube

sensor.battery_158d00028f8633:
  friendly_name: Kitchen Cube Battery

#################################################################
## @Device: Library Bulb 1
#################################################################
light.philips_ltg002_07a6cd08_level_light_color_on_off:
  friendly_name: Library Bulb 1

#################################################################
## @Device: Library Bulb 2
#################################################################
light.philips_ltg002_ce567909_level_light_color_on_off:
  friendly_name: Library Bulb 2

#################################################################
## @Device: Library Bulb 3
#################################################################
light.philips_ltg002_0e63c908_level_light_color_on_off:
  friendly_name: Library Bulb 3

#################################################################
## @Device: Library Bulb 4
#################################################################
light.philips_ltg002_f2c87209_level_light_color_on_off:
  friendly_name: Library Bulb 4

#################################################################
## @Device: Library Bulb 5
#################################################################
light.philips_ltg002_3fb26c09_level_light_color_on_off:
  friendly_name: Library Bulb 5

#################################################################
## @Device: Library Bulb 6
#################################################################
light.philips_ltg002_ae417109_level_light_color_on_off:
  friendly_name: Library Bulb 6

#################################################################
## @Device: Living Room Door Sensor
#################################################################
binary_sensor.door_window_sensor_158d0002b771b8:
  friendly_name: Living Room Door Sensor

sensor.battery_158d0002b771b8:
  friendly_name: Living Room Door Magnet Battery

#################################################################
## @Device: Roof Front Door
#################################################################
binary_sensor.door_window_sensor_158d0002b7b84e:
  friendly_name: Roof Front Door Sensor

sensor.battery_158d0002b7b84e:
  friendly_name: Roof Front Door Magnet Battery

#################################################################
## @Device: Roof Back Door
#################################################################
binary_sensor.door_window_sensor_158d0002c628be:
  friendly_name: Roof Back Door Sensor

sensor.battery_158d0002c628be:
  friendly_name: Roof Back Door Magnet Battery

#################################################################
## @Device: Shower Water Heater Switch
#################################################################
switch.spare_bathroom_water_heater_sw:
  friendly_name: Shower Water Heater
  icon: mdi:water