#################################################################
## @Device: Kitchen AC
#################################################################
climate.1e5418e7:
  friendly_name: Kitchen Air Condition

#################################################################
## @Device: Living Room AC
#################################################################
climate.1e541900:
  friendly_name: Living Room Air Condition

#################################################################
## @Device: Study AC
#################################################################
climate.1ebfaa4e:
  friendly_name: Study Air Condition

#################################################################
## @Device: Nursery AC
#################################################################
climate.c6663ec6:
  friendly_name: Nursery Air Condition

#################################################################
## @Device: Bedroom AC
#################################################################
climate.c6004175:
  friendly_name: Bedroom Air Condition

#################################################################
## @Device: Living Room Table Switch
#################################################################
binary_sensor.switch_158d0003e7c53f:
  friendly_name: Living Room Table Switch

sensor.battery_158d0003e7c53f:
  friendly_name: Living Room Table Switch Battery
  
#################################################################
## @Device: Living Room Smart Plug
#################################################################
switch.living_room_bulb_1_socket_1:
  friendly_name: Living Room Bulb 1
  icon: mdi:lightbulb

#################################################################
## @Device: Nursery Smart Plug
#################################################################
switch.bedroom_bulb_3_socket_1:
  friendly_name: Nursery Wardrobe Lights
  icon: mdi:lightbulb

#################################################################
## @Device: Living Room Light 1
#################################################################
light.living_room_lights:
  friendly_name: Living Room Light 1

#################################################################
## @Device: Dining Room Light 1
#################################################################
light.dining_room_lights:
  friendly_name: Dining Room Light 1

#################################################################
## @Device: Dining Room Light 2
#################################################################
light.dining_room_lights_2:
  friendly_name: Dining Room Light 2

#################################################################
## @Device: Dining Room Cube
#################################################################
binary_sensor.cube_158d0005d41224:
  friendly_name: Dining Room Cube

sensor.battery_158d0005d41224:
  friendly_name: Dining Room Cube Battery

#################################################################
## @Device: Kitchen Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d0003ce12be:
  friendly_name: Kitchen Motion Sensor

sensor.battery_158d0003ce12be:
  friendly_name: Kitchen Motion Sensor Battery

#################################################################
## @Device: Hall Motion Sensor
#################################################################
binary_sensor.lumi_lumi_sensor_motion_7c3b4102_ias_zone:
  friendly_name: Hall Motion Sensor

sensor.lumi_lumi_sensor_motion_7c3b4102_power:
  friendly_name: Hall Motion Sensor Battery

#################################################################
## @Device: Library Motion Sensor
#################################################################
binary_sensor.lumi_lumi_sensor_motion_1b12ce03_ias_zone:
  friendly_name: Library Motion Sensor 1

sensor.lumi_lumi_sensor_motion_1b12ce03_power:
  friendly_name: Library Motion Sensor 1 Battery

#################################################################
## @Device: Library Motion Sensor 2
#################################################################
binary_sensor.lumi_lumi_sensor_motion_3013ce03_ias_zone:
  friendly_name: Library Motion Sensor 2
sensor.lumi_lumi_sensor_motion_3013ce03_power:
  friendly_name: Library Motion Sensor 2 Battery

#################################################################
## @Device: Study Motion Sensor
#################################################################
binary_sensor.lumi_lumi_sensor_motion_34464102_ias_zone:
  friendly_name: Study Motion Sensor

sensor.lumi_lumi_sensor_motion_34464102_power:
  friendly_name: Study Motion Sensor Battery

#################################################################
## @Device: Study Motion Sensor 2
#################################################################
binary_sensor.lumi_lumi_sensor_motion_aq2_836eef07_ias_zone:
  friendly_name: Study Motion Sensor 2

sensor.lumi_lumi_sensor_motion_aq2_836eef07_power:
  friendly_name: Study Motion Sensor 2 Battery

#################################################################
## @Device: Nursery Motion Sensor
#################################################################
binary_sensor.lumi_lumi_sensor_motion_5fc73e02_ias_zone:
  friendly_name: Nursery Motion Sensor

sensor.lumi_lumi_sensor_motion_5fc73e02_power:
  friendly_name: Nursery Motion Sensor Battery

#################################################################
## @Device: Nursery Temperature Sensor
#################################################################
sensor.lumi_lumi_weather_8a81f207_temperature:
  friendly_name: Nursery Temperature

sensor.lumi_lumi_weather_8a81f207_power:
  friendly_name: Nursery Temperature Battery

#################################################################
## @Device: Staircase Motion Sensor
#################################################################
binary_sensor.motion_sensor_158d0001e19483:
  friendly_name: Staircase Motion Sensor

sensor.battery_158d0001e19483:
  friendly_name: Staircase Motion Sensor 1 Battery

#################################################################
## @Device: Staircase Motion Sensor 2
#################################################################
binary_sensor.lumi_lumi_sensor_motion_aq2_7c50ee07_ias_zone:
  friendly_name: Staircase Motion Sensor 2

sensor.lumi_lumi_sensor_motion_aq2_7c50ee07_power:
  friendly_name: Staircase Motion Sensor 2 Battery

#################################################################
## @Device: Bedroom Cube
#################################################################
binary_sensor.cube_158d00028aefda:
  friendly_name: Bedroom Cube

sensor.battery_158d00028aefda:
  friendly_name: Bedroom Cube Battery

#################################################################
## @Device: Kitchen Cube
#################################################################
binary_sensor.cube_158d00028f8633:
  friendly_name: Kitchen Cube

sensor.battery_158d00028f8633:
  friendly_name: Kitchen Cube Battery

#################################################################
## @Device: Library Bulb 1
#################################################################
light.philips_ltg002_07a6cd08_level_light_color_on_off:
  friendly_name: Library Bulb 1

#################################################################
## @Device: Library Bulb 2
#################################################################
light.philips_ltg002_ce567909_level_light_color_on_off:
  friendly_name: Library Bulb 2

#################################################################
## @Device: Library Bulb 3
#################################################################
light.philips_ltg002_0e63c908_level_light_color_on_off:
  friendly_name: Library Bulb 3

#################################################################
## @Device: Library Bulb 4
#################################################################
light.philips_ltg002_f2c87209_level_light_color_on_off:
  friendly_name: Library Bulb 4

#################################################################
## @Device: Library Bulb 5
#################################################################
light.philips_ltg002_3fb26c09_level_light_color_on_off:
  friendly_name: Library Bulb 5

#################################################################
## @Device: Library Bulb 6
#################################################################
light.philips_ltg002_ae417109_level_light_color_on_off:
  friendly_name: Library Bulb 6

#################################################################
## @Device: Living Room Door Sensor
#################################################################
binary_sensor.door_window_sensor_158d0002b771b8:
  friendly_name: Living Room Door Sensor

sensor.battery_158d0002b771b8:
  friendly_name: Living Room Door Magnet Battery

#################################################################
## @Device: Roof Front Door
#################################################################
binary_sensor.door_window_sensor_158d0002b7b84e:
  friendly_name: Roof Front Door Sensor

sensor.battery_158d0002b7b84e:
  friendly_name: Roof Front Door Magnet Battery

#################################################################
## @Device: Roof Back Door
#################################################################
binary_sensor.door_window_sensor_158d0002c628be:
  friendly_name: Roof Back Door Sensor

sensor.battery_158d0002c628be:
  friendly_name: Roof Back Door Magnet Battery

#################################################################
## @Device: Shower Water Heater Switch
#################################################################
switch.spare_bathroom_water_heater_sw:
  friendly_name: Shower Water Heater
  icon: mdi:water

#################################################################
## @Device: Bedroom Switch
#################################################################
sensor.lumi_lumi_sensor_switch_39219a07_power:
  friendly_name: Bedroom Switch Battery