#################################################################
## discovery
#################################################################

ignore:
  - yeelight
  - xiaomi_gw
  - sonos
  - sabnzbd