#################################################################
## @groups
#################################################################
the_loft_members:
  name: The Loft Members
  entities:
    - device_tracker.iphone
    - device_tracker.jessica_cilia
  all: false