#################################################################
## @home-assistant
#################################################################
name: The Loft
latitude: !secret latitude_home
longitude: !secret longitude_home
customize: !include customize.yaml