shower_morning_time:
  name: Shower Morning Time
  has_date: false
  has_time: true
  initial: '06:00'

shower_evening_time:
  name: Shower Evening Time
  has_date: false
  has_time: true
  initial: '16:00'

light_schedule_time_before:
  name: Light Schedule Time - Before
  has_date: false
  has_time: true
  initial: '08:00'
light_schedule_time_after:
  name: Light Schedule Time - After
  has_date: false
  has_time: true
  initial: '15:00'