night_mode:
  name: Night Mode
  initial: false
  icon: mdi:weather-night

maintenance_mode:
  name: Maintenance Mode
  icon: mdi:iframe-braces

away_mode:
  name: Away Mode
  initial: false
  icon: mdi:iframe-braces

hall_automation_override:
  name: Hall Automation Override
  initial: false
  icon: mdi:robot

rack_room_automation_override:
  name: Rack Room Automation Override
  initial: false
  icon: mdi:robot 

study_automation_override:
  name: Study Automation Override
  initial: false
  icon: mdi:robot

main_staircase_automation_override:
  name: Main Staircase Automation Override
  initial: false
  icon: mdi:robot