################################################################################
## @the-loft-modes
################################################################################
dimmed_mode:
  name: Dimmed Mode
  icon: mdi:home-lightbulb-outline
night_mode:
  name: Night Mode
  icon: mdi:weather-night
maintenance_mode:
  name: Maintenance Mode
  icon: mdi:application-braces
submarine_mode:
  name: Submarine Mode
  icon: mdi:submarine
away_mode:
  name: Away Mode
  icon: mdi:shield-lock
wfh_mode:
  name: Working From Home Mode
  icon: mdi:desk-lamp

################################################################################
## @the-loft-seasons
################################################################################
summer_season_mode:
  name: Summer Season Mode
  icon: mdi:weather-sunny

################################################################################
## @automation-overrides
################################################################################
hall_automation_override:
  name: Hall Automation Override
  icon: mdi:robot
study_automation_override:
  name: Study Automation Override
  icon: mdi:robot
library_automation_override:
  name: Library Automation Override
  icon: mdi:robot
main_staircase_automation_override:
  name: Main Staircase Automation Override
  icon: mdi:robot
kitchen_automation_override:
  name: Kitchen Automation Override
  icon: mdi:robot

################################################################################
## @light time automation-override
################################################################################
light_schedule_time_automation_override:
  name: Light Schedule Automation Override
  icon: mdi:robot