#################################################################
## @ios: actions
#################################################################
push:
  categories:
    - name: Vacuum
      identifier: 'vacuum'
      actions:
        - identifier: 'START_VACUUM'
          title: 'Start Vacuum'
          activationMode: 'background'
          authenticationRequired: true
          destructive: false
          behavior: 'default'