- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_bulb_1
    - light.kitchen_bulb_2

- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_lights
    - light.dining_room_lights_2

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lights

- platform: group
  name: Study Lights
  entities:
    - light.office_light_1
    - light.office_light_2

- platform: group
  name: Hall Lights
  entities:
    - light.hall_bulb

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_bulb_1
    - light.bedroom_bulb_2

- platform: group
  name: Main Staircase Lights
  entities:
    - light.mainstaircase_bulb_1
    - light.mainstaircase_bulb_2

- platform: group
  name: Library Lights
  entities:
    - light.philips_ltg002_07a6cd08_level_light_color_on_off
    - light.philips_ltg002_ce567909_level_light_color_on_off
    - light.philips_ltg002_0e63c908_level_light_color_on_off
    - light.philips_ltg002_f2c87209_level_light_color_on_off
    - light.philips_ltg002_3fb26c09_level_light_color_on_off
    - light.philips_ltg002_ae417109_level_light_color_on_off
