study_plant:
  sensors:
    moisture: sensor.study_plant_moisture
    battery: sensor.study_plant_battery_level
    temperature: sensor.study_plant_temperature
    conductivity: sensor.study_plant_soil_conductivity
    brightness: sensor.study_plant_illuminance
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 10
  max_temperature: 32
  min_brightness: 150
  max_brightness: 600

bonsai:
  sensors:
    moisture: sensor.bonsai_moisture
    battery: sensor.bonsai_battery_level
    temperature: sensor.bonsai_temperature
    conductivity: sensor.bonsai_soil_conductivity
    brightness: sensor.bonsai_illuminance