#################################################################
## @sensors
#################################################################
- platform: google_wifi
- platform: uptime
- platform: version