#################################################################
## @sensors
#################################################################
- platform: google_wifi
  host: 192.168.86.1

- platform: uptime

- platform: version