name: Living Room TV
host: !secret webostv_host
turn_on_action:
  service: wake_on_lan.send_magic_packet
  data:
    mac: !secret webostv_mac
customize:
  sources:
    - Youtube
    - Netflix
    - PS4
    - GO Interactive
    - Smart IPTV