#################################################################
## @component: yeelight
#################################################################
devices:
  !secret yeelight_kitchen_light_1_host:
    name: Kitchen Bulb 1
    model: color2
  !secret yeelight_kitchen_light_2_host:
    name: Kitchen Bulb 2
    model: mono1
  !secret yeelight_hall_light_host:
    name: Hall Bulb
    model: mono1
  !secret yeelight_rack_room_light_1_host:
    name: Rack Room Bulb 1
    model: mono1
  !secret yeelight_rack_room_light_2_host:
    name: Rack Room Bulb 2
    model: mono1
  !secret yeelight_rack_room_light_3_host:
    name: Rack Room Bulb 3
    model: mono1
  !secret yeelight_bedroom_light_1_host:
    name: Bedroom Bulb 1
    model: mono1
  !secret yeelight_bedroom_light_2_host:
    name: Bedroom Bulb 2
    model: mono1
  !secret yeelight_mainstaircase_light_1_host:
    name: Mainstaircase Bulb 1
    model: mono1
  !secret yeelight_mainstaircase_light_2_host:
    name: Mainstaircase Bulb 2
    model: mono1