#################################################################
## @zones
#################################################################

#- name: The Loft
#  latitude: !secret latitude_home
#  longitude: !secret longitude_home
#  radius: 100
#  icon: mdi:home