- id: 'FrontDoorCameraPersonDetectedNotifyMark'
  alias: Front Door Camera / Person Detected / Notify Mark

  #trigger
  trigger:
  - platform: device
    device_id: d13c44efa743cc4de643303acc6ab8ad
    domain: nest
    type: camera_person
  
  #action
  action:
  - service: script.notify_base_app_mark
    data:
      title: "The Loft Notification"
      message: "Front Door Person Detected"