######################################################################################################
# @Automation
# @Room: Master Bedroom
# @Alias: Master Bedroom / Light/ Bulb 1 / On / Set Color
######################################################################################################
- id: 'MasterBedroomLightBulb1OnSetColor'
  alias: Master Bedroom / Light/ Bulb 1 / On / Set Color
  description: 'Adjust Master Bedroom Colors'

  #trigger
  trigger:
    - platform: state
      entity_id: light.bedroom_bulb_1
      from: 'off'
      to: 'on'

  #action
  action:
    - alias: 'Set Light and Dim Lights if Dimmed Mode is On'
      choose:
        # IF Dimmed Mode is On
        conditions:
          - condition: state
            entity_id: input_boolean.dimmed_mode
            state: 'on'

        # Set Color to Dimmed
        sequence:
          - service: yeelight.set_color_temp_scene
            entity_id: light.bedroom_bulb_1
            data:
              kelvin: 4200
              brightness: 1

      # Default Action
      default:
        # Set Color to Regular
        - service: yeelight.set_color_temp_scene
          entity_id: light.bedroom_bulb_1
          data:
            kelvin: 4200
            brightness: 35

  mode: single

######################################################################################################
# @Automation
# @Room: Master Bedroom
# @Alias: Master Bedroom / Light/ Bulb 2 / On / Set Color
######################################################################################################
- id: 'MasterBedroomLightBulb2OnSetColor'
  alias: Master Bedroom / Light/ Bulb 2 / On / Set Color
  description: 'Adjust Master Bedroom Colors'

  #trigger
  trigger:
    - platform: state
      entity_id: light.bedroom_bulb_2
      from: 'off'
      to: 'on'

  #action
  action:
    - alias: 'Set Light and Dim Lights if Dimmed Mode is On'
      choose:
        # IF Dimmed Mode is On
        conditions:
          - condition: state
            entity_id: input_boolean.dimmed_mode
            state: 'on'

        # Set Color to Dimmed
        sequence:
          - service: yeelight.set_color_temp_scene
            entity_id: light.bedroom_bulb_2
            data:
              kelvin: 4200
              brightness: 1

      # Default Action
      default:
        # Set Color to Regular
        - service: yeelight.set_color_temp_scene
          entity_id: light.bedroom_bulb_2
          data:
            kelvin: 4200
            brightness: 35

  mode: single
