######################################################################################################
# @Automation
# @Room: Bedroom
# @Alias: Bedroom Perfume Genie / Time / On
# @Device: Perfume Genie (Rituals)
# @Device_URL: https://www.rituals.com/en-nl/collection-story-perfumegenie.html
# @Trigger:
#  - Time / 21:15:00
# @Condition:
#  - Boolean / Night Mode / Off
# @Action:
#  - Perfume Genie / Turn On
#  - Delay / 15 Minutes
#  - Perfume Genie / Turn Off
######################################################################################################
- id: BedroomPerfumeGenieTimeOn
  alias: Bedroom Perfume Genie / Time / On
  
  # trigger
  trigger:
    - platform: time
      at: "21:15:00"

  #condition
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  
  #action
  action:
    - service: switch.turn_on
      entity_id: switch.jean
    - delay: 00:15:00
    - service: switch.turn_off
      entity_id: switch.jean

  mode: single

######################################################################################################
# @Automation
# @Room: Bedroom
# @Alias: Bedroom Perfume Genie / Check
# @Device: Perfume Genie (Rituals)
# @Device_URL: https://www.rituals.com/en-nl/collection-story-perfumegenie.html
# @Trigger:
#  - Time / 21:35:00
# @Condition:
#  - Perfume Genie / On
# @Action:
#  - Perfume Genie / Turn Off
#  - Delay / 5 Minutes
#  - Condition / Perfume Genie / On
#  - Notify
######################################################################################################
- id: BedroomPerfumeGenieCheck
  alias: Bedroom Perfume Genie / Check

  # trigger
  trigger:
    - platform: time
      at: "21:35:00"

  #condition
  condition:
    - condition: state
      entity_id: switch.jean
      state: 'on'
  
  #action
  action:
    - service: switch.turn_off
      entity_id: switch.jean
    - delay: 00:05:00
    - condition: state
      entity_id: switch.jean
      state: 'on'
    - service: script.notify_base_tts
      data:
        title: "The Loft Alert"
        message: "Perfume Genie (Jeane) is still powered on. Turn off now."