######################################################################################################
# @Automation
# @Room: Main Staircase
# @Alias: Staircase Sensors / Motion Detected / Switch On Main Staircase
######################################################################################################
- id: 'StaircaseSensorsMotionDetectedSwitchOnMainStaircase'
  alias: Staircase Sensors / Motion Detected / Switch On Main Staircase
  description: 'Switch On Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: group.staircase_motion_sensors
    from: 'off'
    to: 'on'

  #condition
  condition: 
    - condition: state
      entity_id: input_boolean.main_staircase_automation_override
      state: 'off'
  
  #action
  action:
  - service: light.turn_on
    entity_id:
      - light.mainstaircase_bulb_1
      - light.mainstaircase_bulb_2

######################################################################################################
# @Automation
# @Room: Main Staircase
# @Alias: Staircase Sensors / Motion Not Detected / 2 minutes / Switch Off Staircase
######################################################################################################
- id: 'StaircaseSensorsMotionNotDetectedSwitchOffStaircase'
  alias: Staircase Sensors / Motion Not Detected / 2 minutes / Switch Off Staircase
  description: 'Switch Off Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: group.staircase_motion_sensors
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  
  #condition
  condition: 
    - condition: state
      entity_id: input_boolean.main_staircase_automation_override
      state: 'off'
  
  #action
  action:
    - service: light.turn_off
      entity_id:
        - light.mainstaircase_bulb_1
        - light.mainstaircase_bulb_2