######################################################################################################
# @Automation
# @Room: Main Staircase
# @Alias: Staircase Sensor 1 / Motion Detected / Switch On Main Staircase
# @Device: Yeelight LED Bulb 1S (White)
# @Device_URL: https://en.yeelight.com/product/819.html
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Detected
# @Condition:
# - MainStaircase Automation Override / Off
# @Action:
#  - Script / Main Staircase / On
######################################################################################################
- id: 'StaircaseSensor1MotionDetectedSwitchOnMainStaircase'
  alias: Staircase Sensor 1 / Motion Detected / Switch On Main Staircase
  description: 'Switch On Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e19483
    from: 'off'
    to: 'on'

  #condition
  condition: 
    - condition: state
      entity_id: input_boolean.main_staircase_automation_override
      state: 'off'
  
  #action
  action:
  - service: light.turn_on
    entity_id:
      - light.mainstaircase_bulb_1
      - light.mainstaircase_bulb_2

######################################################################################################
# @Automation
# @Room: Main Staircase
# @Alias: Staircase Sensor 1 / Motion Not Detected / Switch Off Staircase
# @Device: Yeelight LED Bulb 1S (White)
# @Device_URL: https://en.yeelight.com/product/819.html
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Not Detected
# @Condition:
# - MainStaircase Automation Override / Off
# @Action:
#  - Script / Main Staircase / Off
######################################################################################################
- id: 'StaircaseSensor1MotionNotDetectedSwitchOffStaircase'
  alias: Staircase Sensor 1 / Motion Not Detected / Switch Off Staircase
  description: 'Switch Off Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001e19483
    from: 'on'
    to: 'off'
  
  #condition
  condition: 
    - condition: state
      entity_id: input_boolean.main_staircase_automation_override
      state: 'off'
  
  #action
  action:
    - service: light.turn_off
      entity_id:
        - light.mainstaircase_bulb_1
        - light.mainstaircase_bulb_2