######################################################################################################
# @Automation
# @Alias: Routine / Night Mode / Turn On
######################################################################################################
- id: 'RoutineNightModeTurnOn'
  alias: Routine / Night Mode / Turn On
  description: 'Turns Night Mode On'

  # trigger
  trigger:
    - platform: time
      at: '23:59:00'

  #condition
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'

  # action
  action:
    # turn on night boolean
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode

######################################################################################################
# @Automation
# @Alias: Routine / Night Mode / Turn Off
######################################################################################################
- id: 'RoutineNightModeTurnOff'
  alias: Routine / Night Mode / Turn Off
  description: 'Turns Night Mode Off'

  # trigger
  trigger:
    - platform: time
      at: '06:00:00'

  #condition
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'

  # action
  action:
    # turn off night boolean
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
    - service: script.routine_night_off
