######################################################################################################
# @Automation
# @Alias: Home Assistant / Health Check / Camera Availability / Alert
# @Device_URL: https://store.google.com/gb/product/google_nest_hub_max?hl=en-GB
# @Device: Nest Camera Outdoor
# @Device_URL: https://store.google.com/gb/product/nest_cam_outdoor?hl=en-GB
# @Trigger:
#  - Time / 10:00:00
#  - State / Binary Sensor / Camera Availability Sensors / On
# @Condition:
#  - Time / 09:00:00 / 22:00:00
#  - State / Binary Sensor / Camera Availability Sensors / On
# @Action:
#  - Notify / Mark
######################################################################################################
- id: 'HomeAssistantHealthCheckCameraAvailabilityAlert'
  alias: Home Assistant / Health Check / Camera Availability / Alert

  #trigger
  trigger:
    - platform: time
      at: !secret health_check_daily_run_time

    - platform: state
      entity_id: binary_sensor.camera_availability_sensors
      to: 'on'
      for:
        minutes: 30
  
  # condition
  condition:
    - condition: time
      after: '09:00:00'
      before: '22:00:00'

    - condition: state
      entity_id: binary_sensor.camera_availability_sensors
      state: 'on'
  
  #action
  action:
  - service: script.notify_base_app_mark
    data:
      title: "The Loft Alert"
      message: >-
        {%- for camera in states.camera %}
          {%- if camera.state|string == "unavailable" %}
        Health Check Failure. {{ camera.name }} is {{ camera.state }}!
          {%- endif %}
        {%- endfor %}