######################################################################################################
# @Automation
# @Room: Hall
# @Alias: Hall Motion Sensor / Motion / Hall Light
######################################################################################################
- id: 'HallMotionSensorMotionHallLight'
  alias: Hall Motion Sensor / Motion / Hall Light

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_7c3b4102_ias_zone
    from: 'off'
    to: 'on'
  
  #condition
  condition:
  - condition: or
    conditions:
      - condition: time
        before: input_datetime.light_schedule_time_before
        after: input_datetime.light_schedule_time_after
      - condition: state
        entity_id: input_boolean.light_schedule_time_automation_override
        state: 'on'
  - condition: state
    entity_id: input_boolean.hall_automation_override
    state: 'off'
  
  #action
  action:
  - service: light.turn_on
    target: light.hall_bulb
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_7c3b4102_ias_zone
      from: "on"
      to: "off"
  - delay:
      seconds: 30
  - service: light.turn_off
    target: light.hall_bulb

######################################################################################################
# @Automation
# @Room: Hall
# @Alias: Hall Motion Sensor / Motion Not Detected / Switch Off Hall
######################################################################################################
# - id: 'HallMotionSensorMotionNotDetectedSwitchOffHall'
#   alias: Hall Motion Sensor / Motion Not Detected / Switch Off Hall

#   #trigger
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.lumi_lumi_sensor_motion_7c3b4102_ias_zone
#     from: 'on'
#     to: 'off'
    
#   condition:
#   - condition: state
#     entity_id: input_boolean.hall_automation_override
#     state: 'off'
  
#   #action
#   action:
#   - service: light.turn_off
#     entity_id: light.hall_bulb