#################################################################
# @Automation
# @Room: Hall
# @Description: Switch On/Off against Motion
# @Device: Yeelight Light Bulbs
# @Device: Xiaomi Motion Sensor
# @Trigger: Motion
# @Action: 
#################################################################
- id: 'HallMotionSensorMotionDetectedSwitchOnHall'
  alias: Hall Motion Sensor / Motion Detected / Switch On Hall
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0002413b7c
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - after: '16:00'
    before: '08:00'
    condition: time
  action:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_on

- id: 'HallMotionSensorMotionNotDetectedSwitchOffHall'
  alias: Hall Motion Sensor / Motion Not Detected / Switch Off Hall
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0002413b7c
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data: {}
    entity_id: light.hall_bulb
    service: light.turn_off