#################################################################
# @Automation
# @Room: Main Staircase
# @Device: Yeelight LED Bulb 1S (White)
# @Device_URL: https://en.yeelight.com/product/819.html
# @Device: Xiaomi Motion Sensor
# @Description: Switch On/Off Lights against Motion
#################################################################
- id: 'StaircaseSensor1MotionDetectedSwitchOnMainStaircase'
  alias: Staircase Sensor 1 / Motion Detected / Switch On Main Staircase
  description: 'Switch On Lights against Motion'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e19483
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: script.turn_on_main_staircase_lights

- id: 'StaircaseSensor1MotionNotDetectedSwitchOffStaircase'
  alias: Staircase Sensor 1 / Motion Not Detected / Switch Off Staircase
  description: 'Switch Off Lights against Motion'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e19483
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: script.turn_off_main_staircase_lights