######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room TV / Smart IPTV / GO Interactive / Volume
# @Device: LG Oled TV C8 55 inch
# @Device_URL: https://www.lg.com/uk/tvs/lg-OLED55C8PLA
# @Device: Sonos Beam
# @Device_URL: https://www.sonos.com/en/shop/beam.html
# @Trigger:
#  - Living Room TV / Source / Smart IPTV
#  - Living Room TV / Source / GO Interactive
# @Condition:
#  - Living Room Soundbar / Volume / NOT / 0.25
# @Action:
#  - Living Room Soundbar / Volume / 0.25
######################################################################################################
- id: 'LivingRoomTVSmartIPTVGOInteractiveVolume'
  alias: Living Room TV / Smart IPTV / GO Interactive / Volume
  description: 'Adjust Living Room Soundbar Volume when Living Room TV Source is IPTV or GO Interactive'
  
  #trigger
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'Smart IPTV') }}"
      for: "00:00:03"
    - platform: template
      value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'GO Interactive') }}"
      for: "00:00:03"
  
  #condition
  condition:
    condition: not
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.living_room_soundbar', 'volume_level', 0.25) }}"

  #action
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: 0.25
  - service: script.notify_base_tv
    data:
      title: "The Loft Notification"
      message: "Volume Automatically Adjusted."

######################################################################################################
# @Automation
# @Room: Living Room
# @Alias: Living Room TV / Netflix / PS4 / Volume
# @Device: LG Oled TV C8 55 inch
# @Device_URL: https://www.lg.com/uk/tvs/lg-OLED55C8PLA
# @Device: Sonos Beam
# @Device_URL: https://www.sonos.com/en/shop/beam.html
# @Trigger:
#  - Living Room TV / Source / Netflix
#  - Living Room TV / Source / PS4
# @Condition:
#  - Living Room Soundbar / Volume / NOT / 0.4
# @Action:
#  - Living Room Soundbar / Volume / 0.4
######################################################################################################
- id: 'LivingRoomTVNetflixVolume'
  alias: Living Room TV / Netflix / PS4 / Volume
  description: 'Adjust Living Room Soundbar Volume when Living Room TV Source is Netflix or PS4'

  #trigger
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'Netflix') }}"
      for: "00:00:03"
    - platform: template
      value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'PS4') }}"
      for: "00:00:03"

  #condition
  condition:
    condition: not
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.living_room_soundbar', 'volume_level', 0.4) }}"

  #action
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: 0.4
  - service: script.notify_base_tv
    data:
      title: "The Loft Notification"
      message: "Volume Automatically Adjusted."



- id: 'LivingRoomTVGOInteractiveOn'
  alias: Living Room TV / GO Interactive / On
  description: 'Switch On GO Interactive Set Top Box On when Living Room is Switched On.'

  #trigger
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'off'
      to: 'on'

    - platform: state
      entity_id: media_player.living_room_tv
      from: 'on'
      to: 'off'
      for: 
        seconds: 5

  #action
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room_rm_pro_remote
        device: GO Interactive
        command:
          - power