- id: 'KitchenACLivingRoomACLivingRoomDoorAlert'
  alias: Kitchen AC / Living Room AC / Living Room Door / Alert
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ (is_state("climate.kitchen_ac", "off") == false) }}'
        - condition: template
          value_template: '{{ (is_state("climate.living_room_ac", "off") == false) }}'
  
  action:
  - delay: 00:03:00
  - condition: template
    value_template: '{{ (is_state("climate.kitchen_ac", "off") == false) }}'
  - condition: template
    value_template: '{{ (is_state("climate.living_room_ac", "off") == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - service: script.notify_tts_base
    data:
      title: "The Loft Alert"
      message: "Living Room Door is Open! Close living room door for Kitchen AC to remain switched on."
  - delay: 00:02:00
  - condition: template
    value_template: '{{ (is_state("climate.kitchen_ac", "off") == false) }}'
  - condition: template
    value_template: '{{ (is_state("climate.living_room_ac", "off") == false) }}'
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - service: climate.turn_off
    entity_id:
      - climate.kitchen_ac
      - climate.living_room_ac
  - service: script.notify_tts_base
    data:
      title: "The Loft Alert"
      message: "Kitchen AC has been switched off."