######################################################################################################
# @Automation
# @Room: Living Room
# @Description: Alerts if Living Room Door is open whilst trying to switch On Living Room Air
# Conditioner. If Living Room door is not closed, Living Room AC is switched off.
# @Device: Gree Air Conditioner / Fairy Series
# @Device_URL: https://btmalta.com/product/gree-fairy-wall-mounted-type/
# @Device: Xiaomi Mi Door Window Sensor
# @Device_URL: https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mi-door-window-sensors/
# @Trigger: Living Room AC Switched On
# @Condition: Living Room Door Open
# @Action: Notifies And Switches Off Living Room AC if Living Room Door is not Closed.
######################################################################################################
- id: 'LivingRoomACLivingRoomDoorAlert'
  alias: Living Room AC / Living Room Door / Alert
  description: "Alerts if Living Room Door is open whilst trying to switch On Living Room Air 
  Conditioner. If Living Room door is not closed, Living Room AC is switched off."
  # trigger
  trigger:
  - platform: template
    value_template: '{{ is_state("climate.living_room_ac", "off") == false }}'
  # condition
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  # action
  action:
  - delay: 00:02:00
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state("climate.living_room_ac", "off") == false) }}'
  - service: script.notify_tts_base
    data:
      title: "The Loft Alert"
      message: "Living Room Door is Open! Close Living Room Door for Living Room AC to remain switched on."
  # action follow up
  - delay: 00:02:00
  - condition: state
    entity_id: binary_sensor.living_room_door_sensor
    state: 'on'
  - condition: template
    value_template: '{{ (is_state("climate.living_room_ac", "off") == false) }}'
  - service: climate.turn_off
    entity_id: climate.living_room_ac
  - service: script.notify_tts_base
    data:
      title: "The Loft Alert"
      message: "Living Room Door is Open! Close Living Room Door for Living Room AC to remain switched on."