######################################################################################################
# @Automation
# @Room: Rack Room
# @Alias: Rack Room Sensor / Motion Detected / Switch On Rack Room
# @Device: Yeelight LED Bulb 1S (White)
# @Device_URL: https://en.yeelight.com/product/819.html
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Detected
# @Condition:
#  - Rack Room Automation Override / Off
# @Action:
#  - Script / Rack Room / On
######################################################################################################
- id: 'RackRoomSensorMotionDetectedSwitchOnRackRoom'
  alias: Rack Room Sensor / Motion Detected / Switch on Rack Room
  description: 'Switch On Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00023ec75f
    from: 'off'
    to: 'on'

  #condition
  condition: 
  - condition: state
    entity_id: input_boolean.rack_room_automation_override
    state: 'off'
  
  #action
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.rack_room_bulb_1
        - light.rack_room_bulb_2
        - light.rack_room_bulb_3


######################################################################################################
# @Automation
# @Room: Rack Room
# @Alias: Rack Room Sensor / Motion Not Detected / Switch Off Rack Room
# @Device: Yeelight LED Bulb 1S (White)
# @Device_URL: https://en.yeelight.com/product/819.html
# @Device: Xiaomi Mi Motion Sensor
# @Device_URL: https://www.scanmalta.com/shop/catalog/product/view/id/23932/s/xiaomi-mi
# -motion-sensor-for-mi-smart-home/
# @Trigger:
#  - Motion / Not Detected
# @Condition:
#  - Rack Room Automation Override / Off
# @Action:
#  - Script / Rack Room / Off
######################################################################################################
- id: 'RackRoomSensorMotionNotDetectedSwitchoffRackRoom'
  alias: Rack Room Sensor / Motion Not Detected / Switch off Rack Room
  description: 'Switch Off Lights against Motion'

  #trigger
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00023ec75f
    from: 'on'
    to: 'off'

  #condition
  condition: 
  - condition: state
    entity_id: input_boolean.rack_room_automation_override
    state: 'off'

  #action
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.rack_room_bulb_1
        - light.rack_room_bulb_2
        - light.rack_room_bulb_3