- platform: template
  sensors:
      
    climate_availability_sensors:
      friendly_name: 'Climate Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{
          states.climate
            |selectattr('state','in',['unavailable'])
            |list|count > 0
        }}

    media_availability_sensors:
      friendly_name: 'Media Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{
          states.media_player
            |selectattr('state','in',['unavailable'])
            |list|count > 0
        }}
        
    camera_availability_sensors:
      friendly_name: 'Camera Availability Sensors'
      delay_on:
        seconds: 60
      value_template: >-
        {{
          states.camera
            |selectattr('state','in',['unavailable'])
            |list|count > 0
        }}