routine_night:
  alias: Routine / Good Night
  sequence:
    # turn On Dimmed and Night Mode
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.dimmed_mode
        - input_boolean.night_mode

    # turn off dimmable lights
    - service: light.turn_off
      entity_id:
        - light.kitchen_lamp
        - light.hall_bulb
        - light.bedroom_bulb_2

    # turn on kitchen lamp, living room lamp, hall and bedroom bulb 2
    - service: light.turn_on
      entity_id:
        - light.kitchen_lamp
        - light.hall_bulb
        - light.bedroom_bulb_2
        - light.sonoff_s26r2zb_f90cc124_on_off

    # check doors and windows
    - service: script.turn_on
      entity_id: script.doors_windows_check

    # turn off air conditioners (apart from Main Bedroom)
    - service: climate.turn_off
      entity_id:
        - climate.1ebfaa4e
        - climate.1e5418e7
        - climate.1e541900
        - climate.c6663ec6

    # turn off fans (apart from Main Bedroom)
    - service: fan.turn_off
      entity_id:
        - fan.zhimi_fan_za5

    # turn off media
    - service: media_player.turn_off
      entity_id:
        - media_player.living_room_tv
        - media_player.kitchen_display
        - media_player.bedroom_wifi
        - media_player.roof_speaker
        - media_player.googlenestpointe662

    # turn off lights
    - service: light.turn_off
      entity_id:
        - light.kitchen_bulb_1
        - light.kitchen_bulb_2
        - light.mainstaircase_bulb_1
        - light.mainstaircase_bulb_2
        - light.nursery_light
        - light.office_light_1
        - light.office_light_2
        - light.dining_room_lights
        - light.dining_room_lights_2
        - light.living_room_lights_2
        - light.bedroom_bulb_1
        - light.philips_ltg002_07a6cd08_level_light_color_on_off
        - light.philips_ltg002_ce567909_level_light_color_on_off
        - light.philips_ltg002_0e63c908_level_light_color_on_off
        - light.philips_ltg002_f2c87209_level_light_color_on_off
        - light.philips_ltg002_3fb26c09_level_light_color_on_off
        - light.philips_ltg002_ae417109_level_light_color_on_off

    # turn off smart plugs
    - service: switch.turn_off
      entity_id:
        - switch.sonoff_s26r2zb_8a82c224_on_off

    # delay
    - delay: '00:04:00'

    # turn off / kitchen and living room
    - service: light.turn_off
      entity_id:
        - light.kitchen_lamp
        - light.sonoff_s26r2zb_f90cc124_on_off

  mode: single

routine_night_off:
  alias: Routine / Good Night / Off
  sequence:
    # Turn Off Dimmed, Submarine and Night Mode
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dimmed_mode
        - input_boolean.night_mode
        - input_boolean.submarine_mode

    # turn off lights
    - service: light.turn_off
      entity_id:
        - light.bedroom_bulb_1
        - light.bedroom_bulb_2

  mode: single
