routine_wfh_break:
  alias: Routine / WFH / Break / On
  sequence:
    # Turn Off Study Lights
    - service: light.turn_off
      data:
        entity_id:
          - light.office_light_1
          - light.office_light_2

    # Turn Off Study Power Outlets (Apart from USB Outlets)
    - service: switch.turn_off
      entity_id:
        - switch.tz3000_o005nuxx_ts011f_931a66fe_on_off
        - switch.tz3000_o005nuxx_ts011f_931a66fe_on_off_2
        - switch.tz3000_o005nuxx_ts011f_931a66fe_on_off_3
        - switch.tz3000_o005nuxx_ts011f_931a66fe_on_off_4

    - choose:
        # If Summer Season
        - conditions:
            - condition: state
              entity_id: input_boolean.summer_season_mode
              state: 'on'
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.1ebfaa4e
              data:
                hvac_mode: 'fan_only'
