notify_base_tts:
  alias: Notify / Base
  sequence:
    - service: script.notify_base_tv
      data:
        title: "{{ title }}"
        message: "{{ message }}"
    - service: script.notify_base_app
      data:
        title: "{{ title }}"
        message: "{{ message }}"
    - service: script.notify_base_living_soundbar
      data:
        title: "{{ title }}"
        message: "{{ message }}"   