notify_base_living_soundbar:
  alias: Notify / Base / Living Room Soundbar
  sequence:

  # take snapshot  
  - service: sonos.snapshot
    data:
      entity_id: media_player.living_room_soundbar
  
  # set volume
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: 0.2

  # play sound effect
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_soundbar
      media_content_id: https://raw.githubusercontent.com/mjcilia/the-loft-ha/main/config/sounds/the_loft_alert.mp3
      media_content_type: music
  
  # wait until tts has finished playing
  - delay: "00:00:04"
  - wait_template: "{{ not is_state('media_player.living_room_soundbar', 'playing') }}"

  # increase volume for tts
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: 0.4

  # play tts messgae
  - service: tts.cloud_say
    data:
      entity_id: media_player.living_room_soundbar
      cache: true
      options:
          gender: female
      message: > 
        {{ title }}. {{ message }}

  # wait until tts has finished playing
  - delay: "00:00:02"
  - wait_template: "{{ not is_state('media_player.living_room_soundbar', 'playing') }}"

  # restore sonos snapshot
  - service: sonos.restore
    data:
      entity_id: media_player.living_room_soundbar
  mode: single
  