notify_base_living_room_tv:
  alias: Notify / Base / TV
  sequence:
    - condition: template
      value_template: "{{ is_state('media_player.living_room_tv', 'on') }}"
    - service: notify.living_room_tv
      data:
        message: "{{ message }}"