notify_base_living_soundbar:
  alias: Notify / Base / TTS
  sequence:
  - service: media_player.turn_on
    entity_id: media_player.living_room_soundbar
  - service: sonos.snapshot
    entity_id: media_player.living_room_soundbar
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: >
        {%- if (states.media_player.living_room_soundbar.state == 'playing') -%}
          {{ state_attr('media_player.living_room_soundbar', 'volume_level') }}
        {%- else -%}
           0.2
        {%- endif -%}
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_soundbar
      media_content_id: https://raw.githubusercontent.com/mjcilia/the-loft-ha/main/config/sounds/the_loft_alert.mp3
      media_content_type: music
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_soundbar
      volume_level: > 
        {{ state_attr('media_player.living_room_soundbar', 'volume_level') + 0.2 }}
  - delay: 00:00:04
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_soundbar
      language: 'en'
  - delay: 00:00:06
  - service: sonos.restore
    entity_id: media_player.living_room_soundbar
  mode: single
  