######################################################################################################
# @Automation
# @Alias: Health Check / Fan
# @Description: Checks and Alerts For Unavailable Fan Entities. Automation is based
# on a seperate custom input boolean and only runs if Summer Season Mode is On. This is due to the fans
# being completely disconnected in the winter.
######################################################################################################
- id: 'HealthCheckFan'
  alias: 'Health Check / Fan'
  description: 'Checks and Alerts For Unavailable Fan Entities. Automation is based on a seperate custom input boolean nd only runs if Summer Season Mode is On. This is due to the fans being completely disconnected in the winter.'

  #trigger
  trigger:
    - platform: time
      at: !secret health_check_daily_run_time

    - platform: state
      entity_id: binary_sensor.fan_availability_sensor
      to: 'on'
      for:
        minutes: 30

  # condition
  condition:
    - condition: time
      after: !secret health_check_alert_after
      before: !secret health_check_alert_before

    - condition: state
      entity_id: binary_sensor.fan_availability_sensor
      state: 'on'

    - condition: state
      entity_id: input_boolean.summer_season_mode
      state: 'on'

  #action
  action:
    - service: script.notify_base_app_mark
      data:
        title: 'The Loft Alert'
        message: 'Health Check Failure! {{ state_attr("binary_sensor.fan_availability_sensor", "message") }}'

  #mode
  mode: single
