######################################################################################################
# @Automation
# @Alias: Home Assistant / Health Check / Wireless Devices Battery Sensors / Alert
# @Description: Checks and Alerts For Low Battery for all Wireless Devices. Automation is based on
# a seperate custom input boolean.
######################################################################################################
- id: 'HomeAssistantHealthCheckDoorWindowSensorsBatteryAlert'
  alias: Home Assistant / Health Check / Wireless Devices Battery Sensors / Alert

  #trigger
  trigger:
    - platform: time
      at: !secret health_check_daily_run_time

    - platform: state
      entity_id: binary_sensor.wireless_devices_battery_sensors
      to: 'on'
      for:
        minutes: 15

  # condition
  condition:
    - condition: time
      after: !secret health_check_alert_after
      before: !secret health_check_alert_before

    - condition: state
      entity_id: binary_sensor.wireless_devices_battery_sensors
      state: 'on'

  #action
  action:
    - service: script.notify_base_app_mark
      data:
        title: 'The Loft Alert'
        message: >-
          {%- for sensor in states %}
            {%- if sensor.attributes.device_class == "battery" and sensor.attributes.voltage %}
              {%- if sensor.state|int < 15 %}
          Health Check Failure. {{ sensor.attributes.friendly_name }} is at {{ sensor.state }}%
              {%- endif %}
            {%- endif %}
          {%- endfor %}
  
  mode: single
